import db, { initDb } from './db';

interface VocabEntry {
  japanese: string;
  hiragana: string;
  romaji: string;
  german: string;
  category: string;
}

const vocabulary: VocabEntry[] = [
  // ========== あいさつ (Begrüßung) ==========
  { japanese: 'おはようございます', hiragana: 'おはようございます', romaji: 'Ohayou gozaimasu', german: 'Guten Morgen (höflich)', category: 'Begrüßung' },
  { japanese: 'おはよう', hiragana: 'おはよう', romaji: 'Ohayou', german: 'Guten Morgen (freundschaftlich)', category: 'Begrüßung' },
  { japanese: 'こんにちは', hiragana: 'こんにちは', romaji: 'Konnichiwa', german: 'Guten Tag / Hallo', category: 'Begrüßung' },
  { japanese: 'こんばんは', hiragana: 'こんばんは', romaji: 'Konbanwa', german: 'Guten Abend', category: 'Begrüßung' },
  { japanese: 'さようなら', hiragana: 'さようなら', romaji: 'Sayounara', german: 'Auf Wiedersehen', category: 'Begrüßung' },
  { japanese: 'おやすみなさい', hiragana: 'おやすみなさい', romaji: 'Oyasuminasai', german: 'Gute Nacht', category: 'Begrüßung' },
  { japanese: 'ありがとうございます', hiragana: 'ありがとうございます', romaji: 'Arigatou gozaimasu', german: 'Vielen Dank', category: 'Begrüßung' },
  { japanese: 'すみません', hiragana: 'すみません', romaji: 'Sumimasen', german: 'Entschuldigung / Verzeihung', category: 'Begrüßung' },
  { japanese: 'ごめんなさい', hiragana: 'ごめんなさい', romaji: 'Gomen nasai', german: 'Es tut mir leid', category: 'Begrüßung' },
  { japanese: 'どうぞ', hiragana: 'どうぞ', romaji: 'Douzo', german: 'Bitte (beim Anbieten)', category: 'Begrüßung' },
  { japanese: 'どういたしまして', hiragana: 'どういたしまして', romaji: 'Dou itashimashite', german: 'Bitte sehr / Gern geschehen', category: 'Begrüßung' },
  { japanese: 'はじめまして', hiragana: 'はじめまして', romaji: 'Hajimemashite', german: 'Freut mich, Sie kennenzulernen', category: 'Begrüßung' },
  { japanese: 'よろしくおねがいします', hiragana: 'よろしくおねがいします', romaji: 'Yoroshiku onegaishimasu', german: 'Ich freue mich auf unsere Zusammenarbeit', category: 'Begrüßung' },

  // ========== 数字 (Zahlen) ==========
  { japanese: '一', hiragana: 'いち', romaji: 'Ichi', german: 'eins', category: 'Zahlen' },
  { japanese: '二', hiragana: 'に', romaji: 'Ni', german: 'zwei', category: 'Zahlen' },
  { japanese: '三', hiragana: 'さん', romaji: 'San', german: 'drei', category: 'Zahlen' },
  { japanese: '四', hiragana: 'し／よん', romaji: 'Shi / Yon', german: 'vier', category: 'Zahlen' },
  { japanese: '五', hiragana: 'ご', romaji: 'Go', german: 'fünf', category: 'Zahlen' },
  { japanese: '六', hiragana: 'ろく', romaji: 'Roku', german: 'sechs', category: 'Zahlen' },
  { japanese: '七', hiragana: 'しち／なな', romaji: 'Shichi / Nana', german: 'sieben', category: 'Zahlen' },
  { japanese: '八', hiragana: 'はち', romaji: 'Hachi', german: 'acht', category: 'Zahlen' },
  { japanese: '九', hiragana: 'く／きゅう', romaji: 'Ku / Kyuu', german: 'neun', category: 'Zahlen' },
  { japanese: '十', hiragana: 'じゅう', romaji: 'Juu', german: 'zehn', category: 'Zahlen' },
  { japanese: '百', hiragana: 'ひゃく', romaji: 'Hyaku', german: 'hundert', category: 'Zahlen' },
  { japanese: '千', hiragana: 'せん', romaji: 'Sen', german: 'tausend', category: 'Zahlen' },

  // ========== 時間 (Zeit) ==========
  { japanese: '今', hiragana: 'いま', romaji: 'Ima', german: 'jetzt / gerade', category: 'Zeit' },
  { japanese: '今日', hiragana: 'きょう', romaji: 'Kyou', german: 'heute', category: 'Zeit' },
  { japanese: '明日', hiragana: 'あした', romaji: 'Ashita', german: 'morgen', category: 'Zeit' },
  { japanese: '昨日', hiragana: 'きのう', romaji: 'Kinou', german: 'gestern', category: 'Zeit' },
  { japanese: '朝', hiragana: 'あさ', romaji: 'Asa', german: 'Morgen (Tageszeit)', category: 'Zeit' },
  { japanese: '昼', hiragana: 'ひる', romaji: 'Hiru', german: 'Mittag', category: 'Zeit' },
  { japanese: '夜', hiragana: 'よる', romaji: 'Yoru', german: 'Abend / Nacht', category: 'Zeit' },
  { japanese: '毎日', hiragana: 'まいにち', romaji: 'Mainichi', german: 'jeden Tag', category: 'Zeit' },
  { japanese: '来週', hiragana: 'らいしゅう', romaji: 'Raishuu', german: 'nächste Woche', category: 'Zeit' },
  { japanese: '先週', hiragana: 'せんしゅう', romaji: 'Senshuu', german: 'letzte Woche', category: 'Zeit' },
  { japanese: '今週', hiragana: 'こんしゅう', romaji: 'Konshuu', german: 'diese Woche', category: 'Zeit' },
  { japanese: '今年', hiragana: 'ことし', romaji: 'Kotoshi', german: 'dieses Jahr', category: 'Zeit' },
  { japanese: '来年', hiragana: 'らいねん', romaji: 'Rainen', german: 'nächstes Jahr', category: 'Zeit' },
  { japanese: '去年', hiragana: 'きょねん', romaji: 'Kyonen', german: 'letztes Jahr', category: 'Zeit' },
  { japanese: '何時', hiragana: 'なんじ', romaji: 'Nanji', german: 'wie viel Uhr', category: 'Zeit' },
  { japanese: '分', hiragana: 'ふん／ぷん', romaji: 'Fun / Pun', german: 'Minute', category: 'Zeit' },
  { japanese: '時間', hiragana: 'じかん', romaji: 'Jikan', german: 'Zeit / Stunde', category: 'Zeit' },

  // ========== 食べ物 (Essen) ==========
  { japanese: 'ご飯', hiragana: 'ごはん', romaji: 'Gohan', german: 'Reis / Mahlzeit', category: 'Essen' },
  { japanese: 'パン', hiragana: 'パン', romaji: 'Pan', german: 'Brot', category: 'Essen' },
  { japanese: '魚', hiragana: 'さかな', romaji: 'Sakana', german: 'Fisch', category: 'Essen' },
  { japanese: '肉', hiragana: 'にく', romaji: 'Niku', german: 'Fleisch', category: 'Essen' },
  { japanese: '卵', hiragana: 'たまご', romaji: 'Tamago', german: 'Ei', category: 'Essen' },
  { japanese: '野菜', hiragana: 'やさい', romaji: 'Yasai', german: 'Gemüse', category: 'Essen' },
  { japanese: '果物', hiragana: 'くだもの', romaji: 'Kudamono', german: 'Obst', category: 'Essen' },
  { japanese: '寿司', hiragana: 'すし', romaji: 'Sushi', german: 'Sushi', category: 'Essen' },
  { japanese: 'てんぷら', hiragana: 'てんぷら', romaji: 'Tenpura', german: 'Tempura', category: 'Essen' },
  { japanese: 'ラーメン', hiragana: 'ラーメン', romaji: 'Raamen', german: 'Ramen (Nudelsuppe)', category: 'Essen' },
  { japanese: 'りんご', hiragana: 'りんご', romaji: 'Ringo', german: 'Apfel', category: 'Essen' },
  { japanese: 'みかん', hiragana: 'みかん', romaji: 'Mikan', german: 'Mandarine', category: 'Essen' },
  { japanese: 'にんじん', hiragana: 'にんじん', romaji: 'Ninjin', german: 'Karotte', category: 'Essen' },
  { japanese: 'たまねぎ', hiragana: 'たまねぎ', romaji: 'Tamanegi', german: 'Zwiebel', category: 'Essen' },
  { japanese: 'とんかつ', hiragana: 'とんかつ', romaji: 'Tonkatsu', german: 'Schweineschnitzel', category: 'Essen' },

  // ========== 飲み物 (Getränke) ==========
  { japanese: '水', hiragana: 'みず', romaji: 'Mizu', german: 'Wasser', category: 'Getränke' },
  { japanese: 'お茶', hiragana: 'おちゃ', romaji: 'Ocha', german: 'Grüner Tee', category: 'Getränke' },
  { japanese: '紅茶', hiragana: 'こうちゃ', romaji: 'Koucha', german: 'Schwarzer Tee', category: 'Getränke' },
  { japanese: 'コーヒー', hiragana: 'コーヒー', romaji: 'Koohii', german: 'Kaffee', category: 'Getränke' },
  { japanese: 'ジュース', hiragana: 'ジュース', romaji: 'Juusu', german: 'Saft', category: 'Getränke' },
  { japanese: 'ビール', hiragana: 'ビール', romaji: 'Biiru', german: 'Bier', category: 'Getränke' },
  { japanese: 'お酒', hiragana: 'おさけ', romaji: 'Osake', german: 'Alkohol / Sake', category: 'Getränke' },
  { japanese: '牛乳', hiragana: 'ぎゅうにゅう', romaji: 'Gyuunyuu', german: 'Milch', category: 'Getränke' },

  // ========== 家族 (Familie) ==========
  { japanese: '父', hiragana: 'ちち', romaji: 'Chichi', german: 'mein Vater', category: 'Familie' },
  { japanese: '母', hiragana: 'はは', romaji: 'Haha', german: 'meine Mutter', category: 'Familie' },
  { japanese: 'お父さん', hiragana: 'おとうさん', romaji: 'Otousan', german: 'Vater (höflich)', category: 'Familie' },
  { japanese: 'お母さん', hiragana: 'おかあさん', romaji: 'Okaasan', german: 'Mutter (höflich)', category: 'Familie' },
  { japanese: '兄', hiragana: 'あに', romaji: 'Ani', german: 'mein älterer Bruder', category: 'Familie' },
  { japanese: '姉', hiragana: 'あね', romaji: 'Ane', german: 'meine ältere Schwester', category: 'Familie' },
  { japanese: '弟', hiragana: 'おとうと', romaji: 'Otouto', german: 'mein jüngerer Bruder', category: 'Familie' },
  { japanese: '妹', hiragana: 'いもうと', romaji: 'Imouto', german: 'meine jüngere Schwester', category: 'Familie' },
  { japanese: '祖父', hiragana: 'そふ', romaji: 'Sofu', german: 'mein Großvater', category: 'Familie' },
  { japanese: '祖母', hiragana: 'そぼ', romaji: 'Sobo', german: 'meine Großmutter', category: 'Familie' },
  { japanese: 'おじいさん', hiragana: 'おじいさん', romaji: 'Ojiisan', german: 'Großvater (höflich)', category: 'Familie' },
  { japanese: 'おばあさん', hiragana: 'おばあさん', romaji: 'Obaasan', german: 'Großmutter (höflich)', category: 'Familie' },
  { japanese: '子供', hiragana: 'こども', romaji: 'Kodomo', german: 'Kind', category: 'Familie' },
  { japanese: '家族', hiragana: 'かぞく', romaji: 'Kazoku', german: 'Familie', category: 'Familie' },

  // ========== 体 (Körper) ==========
  { japanese: '頭', hiragana: 'あたま', romaji: 'Atama', german: 'Kopf', category: 'Körper' },
  { japanese: '目', hiragana: 'め', romaji: 'Me', german: 'Auge(n)', category: 'Körper' },
  { japanese: '耳', hiragana: 'みみ', romaji: 'Mimi', german: 'Ohr(en)', category: 'Körper' },
  { japanese: '鼻', hiragana: 'はな', romaji: 'Hana', german: 'Nase', category: 'Körper' },
  { japanese: '口', hiragana: 'くち', romaji: 'Kuchi', german: 'Mund', category: 'Körper' },
  { japanese: '手', hiragana: 'て', romaji: 'Te', german: 'Hand', category: 'Körper' },
  { japanese: '足', hiragana: 'あし', romaji: 'Ashi', german: 'Fuß / Bein', category: 'Körper' },
  { japanese: '体', hiragana: 'からだ', romaji: 'Karada', german: 'Körper', category: 'Körper' },
  { japanese: '顔', hiragana: 'かお', romaji: 'Kao', german: 'Gesicht', category: 'Körper' },
  { japanese: '髪', hiragana: 'かみ', romaji: 'Kami', german: 'Haar(e)', category: 'Körper' },

  // ========== 場所 (Orte) ==========
  { japanese: '家', hiragana: 'いえ／うち', romaji: 'Ie / Uchi', german: 'Haus / Zuhause', category: 'Orte' },
  { japanese: '学校', hiragana: 'がっこう', romaji: 'Gakkou', german: 'Schule', category: 'Orte' },
  { japanese: '病院', hiragana: 'びょういん', romaji: 'Byouin', german: 'Krankenhaus', category: 'Orte' },
  { japanese: '銀行', hiragana: 'ぎんこう', romaji: 'Ginkou', german: 'Bank', category: 'Orte' },
  { japanese: '郵便局', hiragana: 'ゆうびんきょく', romaji: 'Yuubinkyoku', german: 'Post(amt)', category: 'Orte' },
  { japanese: '駅', hiragana: 'えき', romaji: 'Eki', german: 'Bahnhof', category: 'Orte' },
  { japanese: '店', hiragana: 'みせ', romaji: 'Mise', german: 'Geschäft / Laden', category: 'Orte' },
  { japanese: 'レストラン', hiragana: 'レストラン', romaji: 'Resutoran', german: 'Restaurant', category: 'Orte' },
  { japanese: 'トイレ', hiragana: 'トイレ', romaji: 'Toire', german: 'Toilette', category: 'Orte' },
  { japanese: '出口', hiragana: 'でぐち', romaji: 'Deguchi', german: 'Ausgang', category: 'Orte' },
  { japanese: '入口', hiragana: 'いりぐち', romaji: 'Iriguchi', german: 'Eingang', category: 'Orte' },
  { japanese: '公園', hiragana: 'こうえん', romaji: 'Kouen', german: 'Park', category: 'Orte' },
  { japanese: '図書館', hiragana: 'としょかん', romaji: 'Toshokan', german: 'Bibliothek', category: 'Orte' },
  { japanese: 'スーパー', hiragana: 'スーパー', romaji: 'Suupaa', german: 'Supermarkt', category: 'Orte' },

  // ========== 乗り物 (Verkehrsmittel) ==========
  { japanese: '車', hiragana: 'くるま', romaji: 'Kuruma', german: 'Auto', category: 'Verkehr' },
  { japanese: '電車', hiragana: 'でんしゃ', romaji: 'Densha', german: 'Zug / S-Bahn', category: 'Verkehr' },
  { japanese: 'バス', hiragana: 'バス', romaji: 'Basu', german: 'Bus', category: 'Verkehr' },
  { japanese: '飛行機', hiragana: 'ひこうき', romaji: 'Hikouki', german: 'Flugzeug', category: 'Verkehr' },
  { japanese: '自転車', hiragana: 'じてんしゃ', romaji: 'Jitensha', german: 'Fahrrad', category: 'Verkehr' },
  { japanese: 'タクシー', hiragana: 'タクシー', romaji: 'Takushii', german: 'Taxi', category: 'Verkehr' },
  { japanese: '地下鉄', hiragana: 'ちかてつ', romaji: 'Chikatetsu', german: 'U-Bahn', category: 'Verkehr' },
  { japanese: '船', hiragana: 'ふね', romaji: 'Fune', german: 'Schiff / Boot', category: 'Verkehr' },

  // ========== 自然 (Natur) ==========
  { japanese: '空', hiragana: 'そら', romaji: 'Sora', german: 'Himmel', category: 'Natur' },
  { japanese: '山', hiragana: 'やま', romaji: 'Yama', german: 'Berg', category: 'Natur' },
  { japanese: '川', hiragana: 'かわ', romaji: 'Kawa', german: 'Fluss', category: 'Natur' },
  { japanese: '海', hiragana: 'うみ', romaji: 'Umi', german: 'Meer', category: 'Natur' },
  { japanese: '花', hiragana: 'はな', romaji: 'Hana', german: 'Blume', category: 'Natur' },
  { japanese: '木', hiragana: 'き', romaji: 'Ki', german: 'Baum / Holz', category: 'Natur' },
  { japanese: '月', hiragana: 'つき', romaji: 'Tsuki', german: 'Mond / Monat', category: 'Natur' },
  { japanese: '星', hiragana: 'ほし', romaji: 'Hoshi', german: 'Stern', category: 'Natur' },
  { japanese: '太陽', hiragana: 'たいよう', romaji: 'Taiyou', german: 'Sonne', category: 'Natur' },
  { japanese: '雨', hiragana: 'あめ', romaji: 'Ame', german: 'Regen', category: 'Natur' },
  { japanese: '雪', hiragana: 'ゆき', romaji: 'Yuki', german: 'Schnee', category: 'Natur' },

  // ========== 動物 (Tiere) ==========
  { japanese: '犬', hiragana: 'いぬ', romaji: 'Inu', german: 'Hund', category: 'Tiere' },
  { japanese: '猫', hiragana: 'ねこ', romaji: 'Neko', german: 'Katze', category: 'Tiere' },
  { japanese: '鳥', hiragana: 'とり', romaji: 'Tori', german: 'Vogel', category: 'Tiere' },
  { japanese: '馬', hiragana: 'うま', romaji: 'Uma', german: 'Pferd', category: 'Tiere' },
  { japanese: '牛', hiragana: 'うし', romaji: 'Ushi', german: 'Kuh / Rind', category: 'Tiere' },
  { japanese: '豚', hiragana: 'ぶた', romaji: 'Buta', german: 'Schwein', category: 'Tiere' },
  { japanese: 'うさぎ', hiragana: 'うさぎ', romaji: 'Usagi', german: 'Hase / Kaninchen', category: 'Tiere' },
  { japanese: '熊', hiragana: 'くま', romaji: 'Kuma', german: 'Bär', category: 'Tiere' },

  // ========== 形容詞 (Adjektive) ==========
  { japanese: '大きい', hiragana: 'おおきい', romaji: 'Ookii', german: 'groß', category: 'Adjektive' },
  { japanese: '小さい', hiragana: 'ちいさい', romaji: 'Chiisai', german: 'klein', category: 'Adjektive' },
  { japanese: '高い', hiragana: 'たかい', romaji: 'Takai', german: 'teuer / hoch', category: 'Adjektive' },
  { japanese: '安い', hiragana: 'やすい', romaji: 'Yasui', german: 'günstig / billig', category: 'Adjektive' },
  { japanese: '新しい', hiragana: 'あたらしい', romaji: 'Atarashii', german: 'neu', category: 'Adjektive' },
  { japanese: '古い', hiragana: 'ふるい', romaji: 'Furui', german: 'alt (Dinge)', category: 'Adjektive' },
  { japanese: 'いい', hiragana: 'いい', romaji: 'Ii', german: 'gut', category: 'Adjektive' },
  { japanese: '悪い', hiragana: 'わるい', romaji: 'Warui', german: 'schlecht / böse', category: 'Adjektive' },
  { japanese: '面白い', hiragana: 'おもしろい', romaji: 'Omoshiroi', german: 'interessant / lustig', category: 'Adjektive' },
  { japanese: 'つまらない', hiragana: 'つまらない', romaji: 'Tsumaranai', german: 'langweilig', category: 'Adjektive' },
  { japanese: '難しい', hiragana: 'むずかしい', romaji: 'Muzukashii', german: 'schwierig', category: 'Adjektive' },
  { japanese: '易しい', hiragana: 'やさしい', romaji: 'Yasashii', german: 'einfach / freundlich', category: 'Adjektive' },
  { japanese: '暑い', hiragana: 'あつい', romaji: 'Atsui', german: 'heiß (Wetter)', category: 'Adjektive' },
  { japanese: '寒い', hiragana: 'さむい', romaji: 'Samui', german: 'kalt (Wetter)', category: 'Adjektive' },
  { japanese: 'おいしい', hiragana: 'おいしい', romaji: 'Oishii', german: 'lecker', category: 'Adjektive' },
  { japanese: 'まずい', hiragana: 'まずい', romaji: 'Mazui', german: 'nicht lecker', category: 'Adjektive' },
  { japanese: 'きれい', hiragana: 'きれい', romaji: 'Kirei', german: 'schön / sauber', category: 'Adjektive' },
  { japanese: '静か', hiragana: 'しずか', romaji: 'Shizuka', german: 'ruhig / still', category: 'Adjektive' },
  { japanese: 'にぎやか', hiragana: 'にぎやか', romaji: 'Nigiyaka', german: 'lebhaft / belebt', category: 'Adjektive' },
  { japanese: '元気', hiragana: 'げんき', romaji: 'Genki', german: 'munter / gesund', category: 'Adjektive' },
  { japanese: '長い', hiragana: 'ながい', romaji: 'Nagai', german: 'lang', category: 'Adjektive' },
  { japanese: '短い', hiragana: 'みじかい', romaji: 'Mijikai', german: 'kurz', category: 'Adjektive' },
  { japanese: '早い', hiragana: 'はやい', romaji: 'Hayai', german: 'schnell / früh', category: 'Adjektive' },
  { japanese: '遅い', hiragana: 'おそい', romaji: 'Osoi', german: 'langsam / spät', category: 'Adjektive' },

  // ========== 動詞 (Verben) ==========
  { japanese: '食べる', hiragana: 'たべる', romaji: 'Taberu', german: 'essen', category: 'Verben' },
  { japanese: '飲む', hiragana: 'のむ', romaji: 'Nomu', german: 'trinken', category: 'Verben' },
  { japanese: '見る', hiragana: 'みる', romaji: 'Miru', german: 'sehen / schauen', category: 'Verben' },
  { japanese: '聞く', hiragana: 'きく', romaji: 'Kiku', german: 'hören / fragen', category: 'Verben' },
  { japanese: '読む', hiragana: 'よむ', romaji: 'Yomu', german: 'lesen', category: 'Verben' },
  { japanese: '書く', hiragana: 'かく', romaji: 'Kaku', german: 'schreiben', category: 'Verben' },
  { japanese: '話す', hiragana: 'はなす', romaji: 'Hanasu', german: 'sprechen / reden', category: 'Verben' },
  { japanese: '行く', hiragana: 'いく', romaji: 'Iku', german: 'gehen / fahren', category: 'Verben' },
  { japanese: '来る', hiragana: 'くる', romaji: 'Kuru', german: 'kommen', category: 'Verben' },
  { japanese: '帰る', hiragana: 'かえる', romaji: 'Kaeru', german: 'zurückkehren / nach Hause gehen', category: 'Verben' },
  { japanese: '起きる', hiragana: 'おきる', romaji: 'Okiru', german: 'aufstehen / aufwachen', category: 'Verben' },
  { japanese: '寝る', hiragana: 'ねる', romaji: 'Neru', german: 'schlafen / ins Bett gehen', category: 'Verben' },
  { japanese: 'する', hiragana: 'する', romaji: 'Suru', german: 'tun / machen', category: 'Verben' },
  { japanese: 'ある', hiragana: 'ある', romaji: 'Aru', german: 'vorhanden sein (Sachen)', category: 'Verben' },
  { japanese: 'いる', hiragana: 'いる', romaji: 'Iru', german: 'da sein (Lebewesen)', category: 'Verben' },
  { japanese: '分かる', hiragana: 'わかる', romaji: 'Wakaru', german: 'verstehen / wissen', category: 'Verben' },
  { japanese: '買う', hiragana: 'かう', romaji: 'Kau', german: 'kaufen', category: 'Verben' },
  { japanese: '売る', hiragana: 'うる', romaji: 'Uru', german: 'verkaufen', category: 'Verben' },
  { japanese: '入る', hiragana: 'はいる', romaji: 'Hairu', german: 'eintreten / hineingehen', category: 'Verben' },
  { japanese: '出る', hiragana: 'でる', romaji: 'Deru', german: 'herausgehen / verlassen', category: 'Verben' },
  { japanese: '待つ', hiragana: 'まつ', romaji: 'Matsu', german: 'warten', category: 'Verben' },
  { japanese: '会う', hiragana: 'あう', romaji: 'Au', german: 'treffen / begegnen', category: 'Verben' },
  { japanese: '使う', hiragana: 'つかう', romaji: 'Tsukau', german: 'benutzen / verwenden', category: 'Verben' },
  { japanese: '思う', hiragana: 'おもう', romaji: 'Omou', german: 'denken / meinen', category: 'Verben' },
  { japanese: 'あける', hiragana: 'あける', romaji: 'Akeru', german: 'öffnen', category: 'Verben' },
  { japanese: 'しめる', hiragana: 'しめる', romaji: 'Shimeru', german: 'schließen', category: 'Verben' },

  // ========== 基本語 (Grundwörter) ==========
  { japanese: '私', hiragana: 'わたし', romaji: 'Watashi', german: 'ich / mein', category: 'Grundwörter' },
  { japanese: 'あなた', hiragana: 'あなた', romaji: 'Anata', german: 'du / Sie', category: 'Grundwörter' },
  { japanese: '彼', hiragana: 'かれ', romaji: 'Kare', german: 'er / sein', category: 'Grundwörter' },
  { japanese: '彼女', hiragana: 'かのじょ', romaji: 'Kanojo', german: 'sie (Frau)', category: 'Grundwörter' },
  { japanese: 'これ', hiragana: 'これ', romaji: 'Kore', german: 'dies (hier)', category: 'Grundwörter' },
  { japanese: 'それ', hiragana: 'それ', romaji: 'Sore', german: 'das (da)', category: 'Grundwörter' },
  { japanese: 'あれ', hiragana: 'あれ', romaji: 'Are', german: 'das (dort)', category: 'Grundwörter' },
  { japanese: 'ここ', hiragana: 'ここ', romaji: 'Koko', german: 'hier', category: 'Grundwörter' },
  { japanese: 'そこ', hiragana: 'そこ', romaji: 'Soko', german: 'da / dort', category: 'Grundwörter' },
  { japanese: 'あそこ', hiragana: 'あそこ', romaji: 'Asoko', german: 'da drüben / dort drüben', category: 'Grundwörter' },
  { japanese: '何', hiragana: 'なに／なん', romaji: 'Nani / Nan', german: 'was', category: 'Grundwörter' },
  { japanese: '誰', hiragana: 'だれ', romaji: 'Dare', german: 'wer', category: 'Grundwörter' },
  { japanese: 'どこ', hiragana: 'どこ', romaji: 'Doko', german: 'wo', category: 'Grundwörter' },
  { japanese: 'いつ', hiragana: 'いつ', romaji: 'Itsu', german: 'wann', category: 'Grundwörter' },
  { japanese: 'どれ', hiragana: 'どれ', romaji: 'Dore', german: 'welches', category: 'Grundwörter' },
  { japanese: 'いくら', hiragana: 'いくら', romaji: 'Ikura', german: 'wie viel (Preis)', category: 'Grundwörter' },
  { japanese: 'いくつ', hiragana: 'いくつ', romaji: 'Ikutsu', german: 'wie viele / wie alt', category: 'Grundwörter' },
  { japanese: 'なぜ', hiragana: 'なぜ', romaji: 'Naze', german: 'warum', category: 'Grundwörter' },
  { japanese: 'はい', hiragana: 'はい', romaji: 'Hai', german: 'ja', category: 'Grundwörter' },
  { japanese: 'いいえ', hiragana: 'いいえ', romaji: 'Iie', german: 'nein', category: 'Grundwörter' },

  // ========== 学校 (Schule) ==========
  { japanese: '先生', hiragana: 'せんせい', romaji: 'Sensei', german: 'Lehrer(in)', category: 'Schule' },
  { japanese: '学生', hiragana: 'がくせい', romaji: 'Gakusei', german: 'Student(in)', category: 'Schule' },
  { japanese: '生徒', hiragana: 'せいと', romaji: 'Seito', german: 'Schüler(in)', category: 'Schule' },
  { japanese: '教室', hiragana: 'きょうしつ', romaji: 'Kyoushitsu', german: 'Klassenzimmer', category: 'Schule' },
  { japanese: '本', hiragana: 'ほん', romaji: 'Hon', german: 'Buch', category: 'Schule' },
  { japanese: 'ノート', hiragana: 'ノート', romaji: 'Nooto', german: 'Heft / Notizbuch', category: 'Schule' },
  { japanese: '鉛筆', hiragana: 'えんぴつ', romaji: 'Enpitsu', german: 'Bleistift', category: 'Schule' },
  { japanese: 'ペン', hiragana: 'ペン', romaji: 'Pen', german: 'Kugelschreiber', category: 'Schule' },
  { japanese: '鞄', hiragana: 'かばん', romaji: 'Kaban', german: 'Tasche', category: 'Schule' },
  { japanese: '机', hiragana: 'つくえ', romaji: 'Tsukue', german: 'Schreibtisch', category: 'Schule' },
  { japanese: '椅子', hiragana: 'いす', romaji: 'Isu', german: 'Stuhl', category: 'Schule' },

  // ========== 服 (Kleidung) ==========
  { japanese: 'シャツ', hiragana: 'シャツ', romaji: 'Shatsu', german: 'Hemd / T-Shirt', category: 'Kleidung' },
  { japanese: 'ズボン', hiragana: 'ズボン', romaji: 'Zubon', german: 'Hose', category: 'Kleidung' },
  { japanese: 'スカート', hiragana: 'スカート', romaji: 'Sukaato', german: 'Rock', category: 'Kleidung' },
  { japanese: 'ワンピース', hiragana: 'ワンピース', romaji: 'Wanpiisu', german: 'Kleid', category: 'Kleidung' },
  { japanese: '上着', hiragana: 'うわぎ', romaji: 'Uwagi', german: 'Jacke / Mantel', category: 'Kleidung' },
  { japanese: '靴', hiragana: 'くつ', romaji: 'Kutsu', german: 'Schuhe', category: 'Kleidung' },
  { japanese: '靴下', hiragana: 'くつした', romaji: 'Kutsushita', german: 'Socken', category: 'Kleidung' },
  { japanese: '帽子', hiragana: 'ぼうし', romaji: 'Boushi', german: 'Hut / Mütze', category: 'Kleidung' },
  { japanese: '眼鏡', hiragana: 'めがね', romaji: 'Megane', german: 'Brille', category: 'Kleidung' },

  // ========== Begrüßung (Erweiterung) ==========
  { japanese: 'いってきます', hiragana: 'いってきます', romaji: 'Itte kimasu', german: 'Ich gehe los (beim Weggehen)', category: 'Begrüßung' },
  { japanese: 'いってらっしゃい', hiragana: 'いってらっしゃい', romaji: 'Itterasshai', german: 'Pass auf dich auf (Antwort beim Weggehen)', category: 'Begrüßung' },
  { japanese: 'ただいま', hiragana: 'ただいま', romaji: 'Tadaima', german: 'Ich bin wieder da', category: 'Begrüßung' },
  { japanese: 'おかえりなさい', hiragana: 'おかえりなさい', romaji: 'Okaerinasai', german: 'Willkommen zu Hause', category: 'Begrüßung' },
  { japanese: 'いただきます', hiragana: 'いただきます', romaji: 'Itadakimasu', german: 'Guten Appetit (vor dem Essen)', category: 'Begrüßung' },
  { japanese: 'ごちそうさまでした', hiragana: 'ごちそうさまでした', romaji: 'Gochisousama deshita', german: 'Es hat gut geschmeckt (nach dem Essen)', category: 'Begrüßung' },
  { japanese: 'おじゃまします', hiragana: 'おじゃまします', romaji: 'Ojama shimasu', german: 'Entschuldigung, dass ich störe (beim Eintreten)', category: 'Begrüßung' },

  // ========== Zahlen (Erweiterung) ==========
  { japanese: '万', hiragana: 'まん', romaji: 'Man', german: 'Zehntausend', category: 'Zahlen' },
  { japanese: 'ゼロ', hiragana: 'ゼロ', romaji: 'Zero', german: 'Null', category: 'Zahlen' },
  { japanese: 'ひとつ', hiragana: 'ひとつ', romaji: 'Hitotsu', german: 'eins (universelle Zählform)', category: 'Zahlen' },
  { japanese: 'ふたつ', hiragana: 'ふたつ', romaji: 'Futatsu', german: 'zwei (universelle Zählform)', category: 'Zahlen' },
  { japanese: 'みっつ', hiragana: 'みっつ', romaji: 'Mittsu', german: 'drei (universelle Zählform)', category: 'Zahlen' },
  { japanese: 'よっつ', hiragana: 'よっつ', romaji: 'Yottsu', german: 'vier (universelle Zählform)', category: 'Zahlen' },
  { japanese: 'いつつ', hiragana: 'いつつ', romaji: 'Itsutsu', german: 'fünf (universelle Zählform)', category: 'Zahlen' },
  { japanese: 'むっつ', hiragana: 'むっつ', romaji: 'Muttsu', german: 'sechs (universelle Zählform)', category: 'Zahlen' },
  { japanese: 'ななつ', hiragana: 'ななつ', romaji: 'Nanatsu', german: 'sieben (universelle Zählform)', category: 'Zahlen' },
  { japanese: 'やっつ', hiragana: 'やっつ', romaji: 'Yattsu', german: 'acht (universelle Zählform)', category: 'Zahlen' },
  { japanese: 'ここのつ', hiragana: 'ここのつ', romaji: 'Kokonotsu', german: 'neun (universelle Zählform)', category: 'Zahlen' },
  { japanese: 'とお', hiragana: 'とお', romaji: 'Too', german: 'zehn (universelle Zählform)', category: 'Zahlen' },
  { japanese: '〜本', hiragana: '〜ほん/ぼん/ぽん', romaji: '~hon / bon / pon', german: 'Zählwort für lange Objekte (Stift, Flasche, …)', category: 'Zahlen' },
  { japanese: '〜枚', hiragana: '〜まい', romaji: '~mai', german: 'Zählwort für flache Dinge (Papier, Teller, …)', category: 'Zahlen' },
  { japanese: '〜冊', hiragana: '〜さつ', romaji: '~satsu', german: 'Zählwort für Bücher / Hefte', category: 'Zahlen' },
  { japanese: '〜台', hiragana: '〜だい', romaji: '~dai', german: 'Zählwort für Maschinen / Fahrzeuge', category: 'Zahlen' },
  { japanese: '〜階', hiragana: '〜かい', romaji: '~kai', german: 'Etage / Stockwerk', category: 'Zahlen' },
  { japanese: '〜番', hiragana: '〜ばん', romaji: '~ban', german: 'Nummer (Ordinalzahl)', category: 'Zahlen' },

  // ========== Zeit (Erweiterung) ==========
  { japanese: 'おととい', hiragana: 'おととい', romaji: 'Ototoi', german: 'vorgestern', category: 'Zeit' },
  { japanese: 'あさって', hiragana: 'あさって', romaji: 'Asatte', german: 'übermorgen', category: 'Zeit' },
  { japanese: '今月', hiragana: 'こんげつ', romaji: 'Kongetsu', german: 'dieser Monat', category: 'Zeit' },
  { japanese: '先月', hiragana: 'せんげつ', romaji: 'Sengetsu', german: 'letzter Monat', category: 'Zeit' },
  { japanese: '来月', hiragana: 'らいげつ', romaji: 'Raigetsu', german: 'nächster Monat', category: 'Zeit' },
  { japanese: '半', hiragana: 'はん', romaji: 'Han', german: 'halb (z. B. 3:30 → さんじはん)', category: 'Zeit' },
  { japanese: '週末', hiragana: 'しゅうまつ', romaji: 'Shuumatsu', german: 'Wochenende', category: 'Zeit' },
  { japanese: '朝ご飯', hiragana: 'あさごはん', romaji: 'Asagohan', german: 'Frühstück', category: 'Zeit' },
  { japanese: '昼ご飯', hiragana: 'ひるごはん', romaji: 'Hirugohan', german: 'Mittagessen', category: 'Zeit' },
  { japanese: '晩ご飯', hiragana: 'ばんごはん', romaji: 'Bangohan', german: 'Abendessen', category: 'Zeit' },
  { japanese: 'ごろ', hiragana: 'ごろ', romaji: 'Goro', german: 'ungefähr (bei Zeitangaben)', category: 'Zeit' },
  { japanese: 'たいてい', hiragana: 'たいてい', romaji: 'Taitei', german: 'meistens / gewöhnlich', category: 'Zeit' },
  { japanese: 'ときどき', hiragana: 'ときどき', romaji: 'Tokidoki', german: 'manchmal', category: 'Zeit' },
  { japanese: 'いつも', hiragana: 'いつも', romaji: 'Itsumo', german: 'immer / gewöhnlich', category: 'Zeit' },
  { japanese: 'もうすぐ', hiragana: 'もうすぐ', romaji: 'Mou sugu', german: 'bald / gleich', category: 'Zeit' },
  { japanese: 'さっき', hiragana: 'さっき', romaji: 'Sakki', german: 'vorhin / gerade eben', category: 'Zeit' },
  { japanese: 'あとで', hiragana: 'あとで', romaji: 'Ato de', german: 'später / danach', category: 'Zeit' },
  { japanese: '〜時間', hiragana: '〜じかん', romaji: '~jikan', german: '… Stunden (Dauer)', category: 'Zeit' },

  // ========== Wochentage (neu) ==========
  { japanese: '日曜日', hiragana: 'にちようび', romaji: 'Nichiyoubi', german: 'Sonntag', category: 'Wochentage' },
  { japanese: '月曜日', hiragana: 'げつようび', romaji: 'Getsuyoubi', german: 'Montag', category: 'Wochentage' },
  { japanese: '火曜日', hiragana: 'かようび', romaji: 'Kayoubi', german: 'Dienstag', category: 'Wochentage' },
  { japanese: '水曜日', hiragana: 'すいようび', romaji: 'Suiyoubi', german: 'Mittwoch', category: 'Wochentage' },
  { japanese: '木曜日', hiragana: 'もくようび', romaji: 'Mokuyoubi', german: 'Donnerstag', category: 'Wochentage' },
  { japanese: '金曜日', hiragana: 'きんようび', romaji: 'Kinyoubi', german: 'Freitag', category: 'Wochentage' },
  { japanese: '土曜日', hiragana: 'どようび', romaji: 'Doyoubi', german: 'Samstag', category: 'Wochentage' },

  // ========== Monate (neu) ==========
  { japanese: '一月', hiragana: 'いちがつ', romaji: 'Ichigatsu', german: 'Januar', category: 'Monate' },
  { japanese: '二月', hiragana: 'にがつ', romaji: 'Nigatsu', german: 'Februar', category: 'Monate' },
  { japanese: '三月', hiragana: 'さんがつ', romaji: 'Sangatsu', german: 'März', category: 'Monate' },
  { japanese: '四月', hiragana: 'しがつ', romaji: 'Shigatsu', german: 'April', category: 'Monate' },
  { japanese: '五月', hiragana: 'ごがつ', romaji: 'Gogatsu', german: 'Mai', category: 'Monate' },
  { japanese: '六月', hiragana: 'ろくがつ', romaji: 'Rokugatsu', german: 'Juni', category: 'Monate' },
  { japanese: '七月', hiragana: 'しちがつ', romaji: 'Shichigatsu', german: 'Juli', category: 'Monate' },
  { japanese: '八月', hiragana: 'はちがつ', romaji: 'Hachigatsu', german: 'August', category: 'Monate' },
  { japanese: '九月', hiragana: 'くがつ', romaji: 'Kugatsu', german: 'September', category: 'Monate' },
  { japanese: '十月', hiragana: 'じゅうがつ', romaji: 'Juugatsu', german: 'Oktober', category: 'Monate' },
  { japanese: '十一月', hiragana: 'じゅういちがつ', romaji: 'Juuichigatsu', german: 'November', category: 'Monate' },
  { japanese: '十二月', hiragana: 'じゅうにがつ', romaji: 'Juunigatsu', german: 'Dezember', category: 'Monate' },

  // ========== Essen (Erweiterung) ==========
  { japanese: 'バナナ', hiragana: 'バナナ', romaji: 'Banana', german: 'Banane', category: 'Essen' },
  { japanese: 'ぶどう', hiragana: 'ぶどう', romaji: 'Budou', german: 'Weintraube(n)', category: 'Essen' },
  { japanese: 'もも', hiragana: 'もも', romaji: 'Momo', german: 'Pfirsich', category: 'Essen' },
  { japanese: 'なし', hiragana: 'なし', romaji: 'Nashi', german: 'Birne', category: 'Essen' },
  { japanese: 'いちご', hiragana: 'いちご', romaji: 'Ichigo', german: 'Erdbeere', category: 'Essen' },
  { japanese: 'メロン', hiragana: 'メロン', romaji: 'Melon', german: 'Melone', category: 'Essen' },
  { japanese: 'スイカ', hiragana: 'スイカ', romaji: 'Suika', german: 'Wassermelone', category: 'Essen' },
  { japanese: 'じゃがいも', hiragana: 'じゃがいも', romaji: 'Jagaimo', german: 'Kartoffel', category: 'Essen' },
  { japanese: 'トマト', hiragana: 'トマト', romaji: 'Tomato', german: 'Tomate', category: 'Essen' },
  { japanese: 'キャベツ', hiragana: 'キャベツ', romaji: 'Kyabetsu', german: 'Kohl / Weißkohl', category: 'Essen' },
  { japanese: 'ねぎ', hiragana: 'ねぎ', romaji: 'Negi', german: 'Lauchzwiebel / Porree', category: 'Essen' },
  { japanese: 'きのこ', hiragana: 'きのこ', romaji: 'Kinoko', german: 'Pilz', category: 'Essen' },
  { japanese: '豆腐', hiragana: 'とうふ', romaji: 'Toufu', german: 'Tofu', category: 'Essen' },
  { japanese: '味噌', hiragana: 'みそ', romaji: 'Miso', german: 'Miso (fermentierte Sojabohnenpaste)', category: 'Essen' },
  { japanese: '醤油', hiragana: 'しょうゆ', romaji: 'Shouyu', german: 'Sojasoße', category: 'Essen' },
  { japanese: '砂糖', hiragana: 'さとう', romaji: 'Satou', german: 'Zucker', category: 'Essen' },
  { japanese: '塩', hiragana: 'しお', romaji: 'Shio', german: 'Salz', category: 'Essen' },
  { japanese: 'こしょう', hiragana: 'こしょう', romaji: 'Koshou', german: 'Pfeffer', category: 'Essen' },
  { japanese: 'バター', hiragana: 'バター', romaji: 'Bataa', german: 'Butter', category: 'Essen' },
  { japanese: 'ケーキ', hiragana: 'ケーキ', romaji: 'Keeki', german: 'Kuchen / Torte', category: 'Essen' },
  { japanese: 'アイスクリーム', hiragana: 'アイスクリーム', romaji: 'Aisu kuriimu', german: 'Eis / Eiscreme', category: 'Essen' },
  { japanese: 'チョコレート', hiragana: 'チョコレート', romaji: 'Chokoreeto', german: 'Schokolade', category: 'Essen' },
  { japanese: 'おにぎり', hiragana: 'おにぎり', romaji: 'Onigiri', german: 'Onigiri (Reisballen)', category: 'Essen' },
  { japanese: 'お弁当', hiragana: 'おべんとう', romaji: 'Obentou', german: 'Bento / Lunchbox', category: 'Essen' },
  { japanese: 'カレー', hiragana: 'カレー', romaji: 'Karee', german: 'Curry', category: 'Essen' },
  { japanese: 'そば', hiragana: 'そば', romaji: 'Soba', german: 'Buchweizennudeln', category: 'Essen' },
  { japanese: 'うどん', hiragana: 'うどん', romaji: 'Udon', german: 'Udon-Nudeln', category: 'Essen' },
  { japanese: 'チャーハン', hiragana: 'チャーハン', romaji: 'Chaahan', german: 'Gebratener Reis', category: 'Essen' },
  { japanese: '味噌汁', hiragana: 'みそしる', romaji: 'Miso shiru', german: 'Miso-Suppe', category: 'Essen' },
  { japanese: 'さしみ', hiragana: 'さしみ', romaji: 'Sashimi', german: 'Sashimi (rohes Fischfleisch)', category: 'Essen' },
  { japanese: '牛肉', hiragana: 'ぎゅうにく', romaji: 'Gyuuniku', german: 'Rindfleisch', category: 'Essen' },
  { japanese: '鶏肉', hiragana: 'とりにく', romaji: 'Toriniku', german: 'Hühnchenfleisch', category: 'Essen' },
  { japanese: '豚肉', hiragana: 'ぶたにく', romaji: 'Butaniku', german: 'Schweinefleisch', category: 'Essen' },
  { japanese: '料理', hiragana: 'りょうり', romaji: 'Ryouri', german: 'Kochen / Gericht', category: 'Essen' },
  { japanese: '味', hiragana: 'あじ', romaji: 'Aji', german: 'Geschmack', category: 'Essen' },
  { japanese: 'ほうれん草', hiragana: 'ほうれんそう', romaji: 'Hourensou', german: 'Spinat', category: 'Essen' },
  { japanese: 'なす', hiragana: 'なす', romaji: 'Nasu', german: 'Aubergine', category: 'Essen' },
  { japanese: 'きゅうり', hiragana: 'きゅうり', romaji: 'Kyuuri', german: 'Gurke', category: 'Essen' },
  { japanese: 'とうもろこし', hiragana: 'とうもろこし', romaji: 'Toumorokoshi', german: 'Mais', category: 'Essen' },
  { japanese: 'スパゲッティ', hiragana: 'スパゲッティ', romaji: 'Supagetti', german: 'Spaghetti', category: 'Essen' },

  // ========== Getränke (Erweiterung) ==========
  { japanese: 'ワイン', hiragana: 'ワイン', romaji: 'Wain', german: 'Wein', category: 'Getränke' },
  { japanese: 'ミネラルウォーター', hiragana: 'ミネラルウォーター', romaji: 'Mineraru wootaa', german: 'Mineralwasser', category: 'Getränke' },
  { japanese: 'アイスコーヒー', hiragana: 'アイスコーヒー', romaji: 'Aisu koohii', german: 'Eiskaffee', category: 'Getränke' },
  { japanese: 'アイスティー', hiragana: 'アイスティー', romaji: 'Aisu tii', german: 'Eistee', category: 'Getränke' },
  { japanese: 'ホットミルク', hiragana: 'ホットミルク', romaji: 'Hotto miruku', german: 'Heiße Milch', category: 'Getränke' },
  { japanese: 'カルピス', hiragana: 'カルピス', romaji: 'Karupisu', german: 'Calpis (japanisches Milchgetränk)', category: 'Getränke' },

  // ========== Familie (Erweiterung) ==========
  { japanese: '兄弟', hiragana: 'きょうだい', romaji: 'Kyoudai', german: 'Geschwister', category: 'Familie' },
  { japanese: '親', hiragana: 'おや', romaji: 'Oya', german: 'Elternteil / Eltern', category: 'Familie' },
  { japanese: '夫', hiragana: 'おっと', romaji: 'Otto', german: 'mein Ehemann', category: 'Familie' },
  { japanese: '妻', hiragana: 'つま', romaji: 'Tsuma', german: 'meine Ehefrau', category: 'Familie' },
  { japanese: '息子', hiragana: 'むすこ', romaji: 'Musuko', german: 'Sohn', category: 'Familie' },
  { japanese: '娘', hiragana: 'むすめ', romaji: 'Musume', german: 'Tochter', category: 'Familie' },
  { japanese: '叔父', hiragana: 'おじ', romaji: 'Oji', german: 'Onkel', category: 'Familie' },
  { japanese: '叔母', hiragana: 'おば', romaji: 'Oba', german: 'Tante', category: 'Familie' },

  // ========== Körper (Erweiterung) ==========
  { japanese: '首', hiragana: 'くび', romaji: 'Kubi', german: 'Hals / Nacken', category: 'Körper' },
  { japanese: '肩', hiragana: 'かた', romaji: 'Kata', german: 'Schulter', category: 'Körper' },
  { japanese: '背中', hiragana: 'せなか', romaji: 'Senaka', german: 'Rücken', category: 'Körper' },
  { japanese: 'お腹', hiragana: 'おなか', romaji: 'Onaka', german: 'Bauch / Magen', category: 'Körper' },
  { japanese: '胸', hiragana: 'むね', romaji: 'Mune', german: 'Brust', category: 'Körper' },
  { japanese: '腕', hiragana: 'うで', romaji: 'Ude', german: 'Arm', category: 'Körper' },
  { japanese: '指', hiragana: 'ゆび', romaji: 'Yubi', german: 'Finger / Zeh', category: 'Körper' },
  { japanese: '歯', hiragana: 'は', romaji: 'Ha', german: 'Zahn / Zähne', category: 'Körper' },

  // ========== Orte (Erweiterung) ==========
  { japanese: '大学', hiragana: 'だいがく', romaji: 'Daigaku', german: 'Universität', category: 'Orte' },
  { japanese: '会社', hiragana: 'かいしゃ', romaji: 'Kaisha', german: 'Firma / Büro', category: 'Orte' },
  { japanese: 'ホテル', hiragana: 'ホテル', romaji: 'Hoteru', german: 'Hotel', category: 'Orte' },
  { japanese: 'アパート', hiragana: 'アパート', romaji: 'Apaato', german: 'Apartment / Mietwohnung', category: 'Orte' },
  { japanese: '神社', hiragana: 'じんじゃ', romaji: 'Jinja', german: 'Shinto-Schrein', category: 'Orte' },
  { japanese: 'お寺', hiragana: 'おてら', romaji: 'Otera', german: 'Buddhistischer Tempel', category: 'Orte' },
  { japanese: '映画館', hiragana: 'えいがかん', romaji: 'Eigakan', german: 'Kino', category: 'Orte' },
  { japanese: '空港', hiragana: 'くうこう', romaji: 'Kuukou', german: 'Flughafen', category: 'Orte' },
  { japanese: '港', hiragana: 'みなと', romaji: 'Minato', german: 'Hafen', category: 'Orte' },
  { japanese: '橋', hiragana: 'はし', romaji: 'Hashi', german: 'Brücke', category: 'Orte' },
  { japanese: '道', hiragana: 'みち', romaji: 'Michi', german: 'Straße / Weg', category: 'Orte' },
  { japanese: '角', hiragana: 'かど', romaji: 'Kado', german: 'Ecke / Straßenecke', category: 'Orte' },
  { japanese: '近く', hiragana: 'ちかく', romaji: 'Chikaku', german: 'in der Nähe', category: 'Orte' },
  { japanese: '遠く', hiragana: 'とおく', romaji: 'Tooku', german: 'weit weg / in der Ferne', category: 'Orte' },
  { japanese: '日本', hiragana: 'にほん', romaji: 'Nihon', german: 'Japan', category: 'Orte' },
  { japanese: '外国', hiragana: 'がいこく', romaji: 'Gaikoku', german: 'Ausland', category: 'Orte' },

  // ========== Verkehr (Erweiterung) ==========
  { japanese: '新幹線', hiragana: 'しんかんせん', romaji: 'Shinkansen', german: 'Shinkansen (Hochgeschwindigkeitszug)', category: 'Verkehr' },
  { japanese: '切符', hiragana: 'きっぷ', romaji: 'Kippu', german: 'Fahrkarte / Ticket', category: 'Verkehr' },
  { japanese: '駐車場', hiragana: 'ちゅうしゃじょう', romaji: 'Chuushajou', german: 'Parkplatz', category: 'Verkehr' },
  { japanese: '信号', hiragana: 'しんごう', romaji: 'Shingou', german: 'Ampel', category: 'Verkehr' },
  { japanese: '地図', hiragana: 'ちず', romaji: 'Chizu', german: 'Landkarte / Stadtplan', category: 'Verkehr' },
  { japanese: 'まっすぐ', hiragana: 'まっすぐ', romaji: 'Massugu', german: 'geradeaus', category: 'Verkehr' },
  { japanese: '乗り換え', hiragana: 'のりかえ', romaji: 'Norikae', german: 'Umsteigen (Zug/Bus)', category: 'Verkehr' },

  // ========== Natur (Erweiterung) ==========
  { japanese: '森', hiragana: 'もり', romaji: 'Mori', german: 'Wald', category: 'Natur' },
  { japanese: '草', hiragana: 'くさ', romaji: 'Kusa', german: 'Gras / Kraut', category: 'Natur' },
  { japanese: '葉', hiragana: 'は', romaji: 'Ha', german: 'Blatt / Laub', category: 'Natur' },
  { japanese: '池', hiragana: 'いけ', romaji: 'Ike', german: 'Teich', category: 'Natur' },
  { japanese: '湖', hiragana: 'みずうみ', romaji: 'Mizuumi', german: 'See (stehendes Gewässer)', category: 'Natur' },
  { japanese: '島', hiragana: 'しま', romaji: 'Shima', german: 'Insel', category: 'Natur' },
  { japanese: '石', hiragana: 'いし', romaji: 'Ishi', german: 'Stein', category: 'Natur' },
  { japanese: '土', hiragana: 'つち', romaji: 'Tsuchi', german: 'Erde / Boden', category: 'Natur' },
  { japanese: '春', hiragana: 'はる', romaji: 'Haru', german: 'Frühling', category: 'Natur' },
  { japanese: '夏', hiragana: 'なつ', romaji: 'Natsu', german: 'Sommer', category: 'Natur' },
  { japanese: '秋', hiragana: 'あき', romaji: 'Aki', german: 'Herbst', category: 'Natur' },
  { japanese: '冬', hiragana: 'ふゆ', romaji: 'Fuyu', german: 'Winter', category: 'Natur' },
  { japanese: '季節', hiragana: 'きせつ', romaji: 'Kisetsu', german: 'Jahreszeit', category: 'Natur' },
  { japanese: '火', hiragana: 'ひ', romaji: 'Hi', german: 'Feuer / Flamme', category: 'Natur' },

  // ========== Tiere (Erweiterung) ==========
  { japanese: '猿', hiragana: 'さる', romaji: 'Saru', german: 'Affe', category: 'Tiere' },
  { japanese: '狐', hiragana: 'きつね', romaji: 'Kitsune', german: 'Fuchs', category: 'Tiere' },
  { japanese: '亀', hiragana: 'かめ', romaji: 'Kame', german: 'Schildkröte', category: 'Tiere' },
  { japanese: '蛙', hiragana: 'かえる', romaji: 'Kaeru', german: 'Frosch', category: 'Tiere' },
  { japanese: '蛇', hiragana: 'へび', romaji: 'Hebi', german: 'Schlange', category: 'Tiere' },
  { japanese: '蟹', hiragana: 'かに', romaji: 'Kani', german: 'Krabbe / Krebs', category: 'Tiere' },
  { japanese: '海老', hiragana: 'えび', romaji: 'Ebi', german: 'Garnele / Shrimp', category: 'Tiere' },
  { japanese: '蛸', hiragana: 'たこ', romaji: 'Tako', german: 'Oktopus / Tintenfisch', category: 'Tiere' },
  { japanese: '虫', hiragana: 'むし', romaji: 'Mushi', german: 'Insekt / Käfer', category: 'Tiere' },
  { japanese: '鹿', hiragana: 'しか', romaji: 'Shika', german: 'Hirsch', category: 'Tiere' },
  { japanese: '象', hiragana: 'ぞう', romaji: 'Zou', german: 'Elefant', category: 'Tiere' },
  { japanese: 'ライオン', hiragana: 'ライオン', romaji: 'Raion', german: 'Löwe', category: 'Tiere' },

  // ========== Farben (neu) ==========
  { japanese: '赤', hiragana: 'あか', romaji: 'Aka', german: 'Rot', category: 'Farben' },
  { japanese: '青', hiragana: 'あお', romaji: 'Ao', german: 'Blau / Grün (Ampel)', category: 'Farben' },
  { japanese: '黄色', hiragana: 'きいろ', romaji: 'Kiiro', german: 'Gelb', category: 'Farben' },
  { japanese: '緑', hiragana: 'みどり', romaji: 'Midori', german: 'Grün', category: 'Farben' },
  { japanese: '黒', hiragana: 'くろ', romaji: 'Kuro', german: 'Schwarz', category: 'Farben' },
  { japanese: '白', hiragana: 'しろ', romaji: 'Shiro', german: 'Weiß', category: 'Farben' },
  { japanese: '茶色', hiragana: 'ちゃいろ', romaji: 'Chairo', german: 'Braun', category: 'Farben' },
  { japanese: 'ピンク', hiragana: 'ピンク', romaji: 'Pinku', german: 'Rosa / Pink', category: 'Farben' },
  { japanese: 'オレンジ', hiragana: 'オレンジ', romaji: 'Orenji', german: 'Orange', category: 'Farben' },
  { japanese: '紫', hiragana: 'むらさき', romaji: 'Murasaki', german: 'Lila / Violett', category: 'Farben' },
  { japanese: '灰色', hiragana: 'はいいろ', romaji: 'Haiiro', german: 'Grau', category: 'Farben' },
  { japanese: '金色', hiragana: 'きんいろ', romaji: 'Kin\'iro', german: 'Gold(farben)', category: 'Farben' },
  { japanese: '銀色', hiragana: 'ぎんいろ', romaji: 'Gin\'iro', german: 'Silber(farben)', category: 'Farben' },

  // ========== Wetter (neu) ==========
  { japanese: '天気', hiragana: 'てんき', romaji: 'Tenki', german: 'Wetter', category: 'Wetter' },
  { japanese: '晴れ', hiragana: 'はれ', romaji: 'Hare', german: 'Sonniges Wetter / heiter', category: 'Wetter' },
  { japanese: '曇り', hiragana: 'くもり', romaji: 'Kumori', german: 'Bewölkt / bedeckt', category: 'Wetter' },
  { japanese: '風', hiragana: 'かぜ', romaji: 'Kaze', german: 'Wind', category: 'Wetter' },
  { japanese: '台風', hiragana: 'たいふう', romaji: 'Taifuu', german: 'Taifun', category: 'Wetter' },
  { japanese: '霧', hiragana: 'きり', romaji: 'Kiri', german: 'Nebel', category: 'Wetter' },
  { japanese: '虹', hiragana: 'にじ', romaji: 'Niji', german: 'Regenbogen', category: 'Wetter' },
  { japanese: '雷', hiragana: 'かみなり', romaji: 'Kaminari', german: 'Donner / Gewitter', category: 'Wetter' },
  { japanese: '気温', hiragana: 'きおん', romaji: 'Kion', german: 'Temperatur (Luft)', category: 'Wetter' },
  { japanese: '暖かい', hiragana: 'あたたかい', romaji: 'Atatakai', german: 'warm (Wetter / Gefühl)', category: 'Wetter' },
  { japanese: '涼しい', hiragana: 'すずしい', romaji: 'Suzushii', german: 'kühl / angenehm frisch', category: 'Wetter' },
  { japanese: '蒸し暑い', hiragana: 'むしあつい', romaji: 'Mushiatsui', german: 'schwül / drückend heiß', category: 'Wetter' },
  { japanese: '冷たい', hiragana: 'つめたい', romaji: 'Tsumetai', german: 'kalt (bei Berührung)', category: 'Wetter' },
  { japanese: '氷', hiragana: 'こおり', romaji: 'Koori', german: 'Eis / Eiswürfel', category: 'Wetter' },
  { japanese: '吹雪', hiragana: 'ふぶき', romaji: 'Fubuki', german: 'Schneesturm', category: 'Wetter' },
  { japanese: '天気予報', hiragana: 'てんきよほう', romaji: 'Tenki yohou', german: 'Wettervorhersage', category: 'Wetter' },

  // ========== Wohnung (neu) ==========
  { japanese: '部屋', hiragana: 'へや', romaji: 'Heya', german: 'Zimmer / Raum', category: 'Wohnung' },
  { japanese: 'ドア', hiragana: 'ドア', romaji: 'Doa', german: 'Tür', category: 'Wohnung' },
  { japanese: '窓', hiragana: 'まど', romaji: 'Mado', german: 'Fenster', category: 'Wohnung' },
  { japanese: '階段', hiragana: 'かいだん', romaji: 'Kaidan', german: 'Treppe', category: 'Wohnung' },
  { japanese: '庭', hiragana: 'にわ', romaji: 'Niwa', german: 'Garten', category: 'Wohnung' },
  { japanese: '台所', hiragana: 'だいどころ', romaji: 'Daidokoro', german: 'Küche', category: 'Wohnung' },
  { japanese: 'リビング', hiragana: 'リビング', romaji: 'Ribingu', german: 'Wohnzimmer', category: 'Wohnung' },
  { japanese: 'ベッド', hiragana: 'ベッド', romaji: 'Beddo', german: 'Bett', category: 'Wohnung' },
  { japanese: 'テーブル', hiragana: 'テーブル', romaji: 'Teeburu', german: 'Tisch', category: 'Wohnung' },
  { japanese: 'テレビ', hiragana: 'テレビ', romaji: 'Terebi', german: 'Fernseher', category: 'Wohnung' },
  { japanese: 'ラジオ', hiragana: 'ラジオ', romaji: 'Rajio', german: 'Radio', category: 'Wohnung' },
  { japanese: '電話', hiragana: 'でんわ', romaji: 'Denwa', german: 'Telefon', category: 'Wohnung' },
  { japanese: '冷蔵庫', hiragana: 'れいぞうこ', romaji: 'Reizouko', german: 'Kühlschrank', category: 'Wohnung' },
  { japanese: '時計', hiragana: 'とけい', romaji: 'Tokei', german: 'Uhr (Gerät)', category: 'Wohnung' },
  { japanese: '鏡', hiragana: 'かがみ', romaji: 'Kagami', german: 'Spiegel', category: 'Wohnung' },
  { japanese: '傘', hiragana: 'かさ', romaji: 'Kasa', german: 'Regenschirm', category: 'Wohnung' },
  { japanese: 'カーテン', hiragana: 'カーテン', romaji: 'Kaaten', german: 'Vorhang / Gardine', category: 'Wohnung' },
  { japanese: 'ソファ', hiragana: 'ソファ', romaji: 'Sofa', german: 'Sofa / Couch', category: 'Wohnung' },
  { japanese: '棚', hiragana: 'たな', romaji: 'Tana', german: 'Regal / Ablage', category: 'Wohnung' },
  { japanese: '布団', hiragana: 'ふとん', romaji: 'Futon', german: 'Futon / Bettdecke', category: 'Wohnung' },
  { japanese: '枕', hiragana: 'まくら', romaji: 'Makura', german: 'Kissen / Kopfkissen', category: 'Wohnung' },
  { japanese: 'タオル', hiragana: 'タオル', romaji: 'Taoru', german: 'Handtuch', category: 'Wohnung' },
  { japanese: '石鹸', hiragana: 'せっけん', romaji: 'Sekken', german: 'Seife', category: 'Wohnung' },
  { japanese: 'シャワー', hiragana: 'シャワー', romaji: 'Shawaa', german: 'Dusche', category: 'Wohnung' },
  { japanese: '電気', hiragana: 'でんき', romaji: 'Denki', german: 'Licht / Elektrizität / Strom', category: 'Wohnung' },
  { japanese: '鍵', hiragana: 'かぎ', romaji: 'Kagi', german: 'Schlüssel / Schloss', category: 'Wohnung' },
  { japanese: 'ゴミ', hiragana: 'ごみ', romaji: 'Gomi', german: 'Müll / Abfall', category: 'Wohnung' },
  { japanese: 'ポスト', hiragana: 'ポスト', romaji: 'Posuto', german: 'Briefkasten / Post', category: 'Wohnung' },

  // ========== Gesundheit (neu) ==========
  { japanese: '病気', hiragana: 'びょうき', romaji: 'Byouki', german: 'Krankheit / krank sein', category: 'Gesundheit' },
  { japanese: '風邪', hiragana: 'かぜ', romaji: 'Kaze', german: 'Erkältung / Grippe', category: 'Gesundheit' },
  { japanese: '痛い', hiragana: 'いたい', romaji: 'Itai', german: 'schmerzhaft / es tut weh', category: 'Gesundheit' },
  { japanese: '薬', hiragana: 'くすり', romaji: 'Kusuri', german: 'Medikament / Arznei', category: 'Gesundheit' },
  { japanese: '医者', hiragana: 'いしゃ', romaji: 'Isha', german: 'Arzt / Ärztin', category: 'Gesundheit' },
  { japanese: '熱', hiragana: 'ねつ', romaji: 'Netsu', german: 'Fieber / Hitze', category: 'Gesundheit' },
  { japanese: '咳', hiragana: 'せき', romaji: 'Seki', german: 'Husten', category: 'Gesundheit' },
  { japanese: '鼻水', hiragana: 'はなみず', romaji: 'Hanamizu', german: 'Schnupfen / laufende Nase', category: 'Gesundheit' },
  { japanese: '頭痛', hiragana: 'ずつう', romaji: 'Zutsuu', german: 'Kopfschmerzen', category: 'Gesundheit' },
  { japanese: '怪我', hiragana: 'けが', romaji: 'Kega', german: 'Verletzung / Wunde', category: 'Gesundheit' },
  { japanese: '傷', hiragana: 'きず', romaji: 'Kizu', german: 'Wunde / Kratzer', category: 'Gesundheit' },
  { japanese: '運動', hiragana: 'うんどう', romaji: 'Undou', german: 'Sport / körperliche Bewegung', category: 'Gesundheit' },
  { japanese: '健康', hiragana: 'けんこう', romaji: 'Kenkou', german: 'Gesundheit / gesund', category: 'Gesundheit' },
  { japanese: '体温', hiragana: 'たいおん', romaji: 'Taion', german: 'Körpertemperatur', category: 'Gesundheit' },
  { japanese: '気分', hiragana: 'きぶん', romaji: 'Kibun', german: 'Befinden / Stimmung', category: 'Gesundheit' },
  { japanese: '注射', hiragana: 'ちゅうしゃ', romaji: 'Chuusha', german: 'Spritze / Injektion', category: 'Gesundheit' },
  { japanese: 'マスク', hiragana: 'マスク', romaji: 'Masuku', german: 'Maske (Mund-Nasen-Schutz)', category: 'Gesundheit' },
  { japanese: '手術', hiragana: 'しゅじゅつ', romaji: 'Shujutsu', german: 'Operation / chirurgischer Eingriff', category: 'Gesundheit' },

  // ========== Adjektive (Erweiterung) ==========
  { japanese: '赤い', hiragana: 'あかい', romaji: 'Akai', german: 'rot', category: 'Adjektive' },
  { japanese: '青い', hiragana: 'あおい', romaji: 'Aoi', german: 'blau / grün (Pflanzenwelt)', category: 'Adjektive' },
  { japanese: '甘い', hiragana: 'あまい', romaji: 'Amai', german: 'süß', category: 'Adjektive' },
  { japanese: '忙しい', hiragana: 'いそがしい', romaji: 'Isogashii', german: 'beschäftigt / viel zu tun', category: 'Adjektive' },
  { japanese: '嬉しい', hiragana: 'うれしい', romaji: 'Ureshii', german: 'froh / erfreut / glücklich', category: 'Adjektive' },
  { japanese: '多い', hiragana: 'おおい', romaji: 'Ooi', german: 'viele / viel (Menge)', category: 'Adjektive' },
  { japanese: '重い', hiragana: 'おもい', romaji: 'Omoi', german: 'schwer (Gewicht)', category: 'Adjektive' },
  { japanese: '悲しい', hiragana: 'かなしい', romaji: 'Kanashii', german: 'traurig', category: 'Adjektive' },
  { japanese: '辛い', hiragana: 'からい', romaji: 'Karai', german: 'scharf (Gewürz) / salzig', category: 'Adjektive' },
  { japanese: '可愛い', hiragana: 'かわいい', romaji: 'Kawaii', german: 'süß / niedlich / hübsch', category: 'Adjektive' },
  { japanese: '怖い', hiragana: 'こわい', romaji: 'Kowai', german: 'angsteinflößend / gruselig', category: 'Adjektive' },
  { japanese: '暗い', hiragana: 'くらい', romaji: 'Kurai', german: 'dunkel / finster', category: 'Adjektive' },
  { japanese: '明るい', hiragana: 'あかるい', romaji: 'Akarui', german: 'hell / fröhlich', category: 'Adjektive' },
  { japanese: '楽しい', hiragana: 'たのしい', romaji: 'Tanoshii', german: 'vergnüglich / spaßig / schön', category: 'Adjektive' },
  { japanese: '強い', hiragana: 'つよい', romaji: 'Tsuyoi', german: 'stark / kräftig', category: 'Adjektive' },
  { japanese: '低い', hiragana: 'ひくい', romaji: 'Hikui', german: 'niedrig / tief', category: 'Adjektive' },
  { japanese: '広い', hiragana: 'ひろい', romaji: 'Hiroi', german: 'weit / geräumig / breit', category: 'Adjektive' },
  { japanese: '欲しい', hiragana: 'ほしい', romaji: 'Hoshii', german: 'haben wollen / wünschen', category: 'Adjektive' },
  { japanese: '丸い', hiragana: 'まるい', romaji: 'Marui', german: 'rund / kreisförmig', category: 'Adjektive' },
  { japanese: '柔らかい', hiragana: 'やわらかい', romaji: 'Yawarakai', german: 'weich / zart', category: 'Adjektive' },
  { japanese: '若い', hiragana: 'わかい', romaji: 'Wakai', german: 'jung', category: 'Adjektive' },
  { japanese: '厚い', hiragana: 'あつい', romaji: 'Atsui', german: 'dick / kompakt (Buch, Brett)', category: 'Adjektive' },
  { japanese: '薄い', hiragana: 'うすい', romaji: 'Usui', german: 'dünn / hell (Farbe) / wässrig', category: 'Adjektive' },
  { japanese: '苦い', hiragana: 'にがい', romaji: 'Nigai', german: 'bitter', category: 'Adjektive' },
  { japanese: '酸っぱい', hiragana: 'すっぱい', romaji: 'Suppai', german: 'sauer / säuerlich', category: 'Adjektive' },
  { japanese: '危ない', hiragana: 'あぶない', romaji: 'Abunai', german: 'gefährlich / Vorsicht!', category: 'Adjektive' },
  { japanese: '親切', hiragana: 'しんせつ', romaji: 'Shinsetsu', german: 'freundlich / nett / zuvorkommend', category: 'Adjektive' },
  { japanese: '真面目', hiragana: 'まじめ', romaji: 'Majime', german: 'ernsthaft / fleißig / gewissenhaft', category: 'Adjektive' },
  { japanese: '便利', hiragana: 'べんり', romaji: 'Benri', german: 'praktisch / bequem / nützlich', category: 'Adjektive' },
  { japanese: '不便', hiragana: 'ふべん', romaji: 'Fuben', german: 'unpraktisch / ungelegen', category: 'Adjektive' },
  { japanese: '下手', hiragana: 'へた', romaji: 'Heta', german: 'ungeschickt / schlecht (in etw.)', category: 'Adjektive' },
  { japanese: '上手', hiragana: 'じょうず', romaji: 'Jouzu', german: 'geschickt / gut (in etw.)', category: 'Adjektive' },
  { japanese: '得意', hiragana: 'とくい', romaji: 'Tokui', german: 'seine Stärke / gut können', category: 'Adjektive' },
  { japanese: '苦手', hiragana: 'にがて', romaji: 'Nigate', german: 'seine Schwäche / schlecht können', category: 'Adjektive' },
  { japanese: '好き', hiragana: 'すき', romaji: 'Suki', german: 'mögen / gernhaben', category: 'Adjektive' },
  { japanese: '嫌い', hiragana: 'きらい', romaji: 'Kirai', german: 'nicht mögen / verabscheuen', category: 'Adjektive' },
  { japanese: '大切', hiragana: 'たいせつ', romaji: 'Taisetsu', german: 'wichtig / wertvoll / kostbar', category: 'Adjektive' },
  { japanese: '大丈夫', hiragana: 'だいじょうぶ', romaji: 'Daijoubu', german: 'in Ordnung / kein Problem', category: 'Adjektive' },
  { japanese: '同じ', hiragana: 'おなじ', romaji: 'Onaji', german: 'gleich / derselbe', category: 'Adjektive' },
  { japanese: '違う', hiragana: 'ちがう', romaji: 'Chigau', german: 'verschieden / falsch / anders sein', category: 'Adjektive' },
  { japanese: '正しい', hiragana: 'ただしい', romaji: 'Tadashii', german: 'richtig / korrekt', category: 'Adjektive' },
  { japanese: '細い', hiragana: 'ほそい', romaji: 'Hosoi', german: 'dünn / schlank (Linie, Person)', category: 'Adjektive' },
  { japanese: '太い', hiragana: 'ふとい', romaji: 'Futoi', german: 'dick / stämmig (Linie, Person)', category: 'Adjektive' },

  // ========== Verben (Erweiterung) ==========
  { japanese: '遊ぶ', hiragana: 'あそぶ', romaji: 'Asobu', german: 'spielen / sich amüsieren', category: 'Verben' },
  { japanese: '洗う', hiragana: 'あらう', romaji: 'Arau', german: 'waschen / spülen', category: 'Verben' },
  { japanese: '歩く', hiragana: 'あるく', romaji: 'Aruku', german: 'laufen / zu Fuß gehen', category: 'Verben' },
  { japanese: '言う', hiragana: 'いう', romaji: 'Iu', german: 'sagen / sprechen', category: 'Verben' },
  { japanese: '入れる', hiragana: 'いれる', romaji: 'Ireru', german: 'hineintun / einlegen', category: 'Verben' },
  { japanese: '動く', hiragana: 'うごく', romaji: 'Ugoku', german: 'sich bewegen / funktionieren', category: 'Verben' },
  { japanese: '歌う', hiragana: 'うたう', romaji: 'Utau', german: 'singen', category: 'Verben' },
  { japanese: '覚える', hiragana: 'おぼえる', romaji: 'Oboeru', german: 'sich merken / auswendig lernen', category: 'Verben' },
  { japanese: '終わる', hiragana: 'おわる', romaji: 'Owaru', german: 'enden / fertig sein (intransitiv)', category: 'Verben' },
  { japanese: '貸す', hiragana: 'かす', romaji: 'Kasu', german: 'ausleihen / verleihen (an jmd.)', category: 'Verben' },
  { japanese: 'かぶる', hiragana: 'かぶる', romaji: 'Kaburu', german: 'aufsetzen (Hut, Mütze)', category: 'Verben' },
  { japanese: '考える', hiragana: 'かんがえる', romaji: 'Kangaeru', german: 'denken / nachdenken / überlegen', category: 'Verben' },
  { japanese: '切る', hiragana: 'きる', romaji: 'Kiru', german: 'schneiden / abschneiden', category: 'Verben' },
  { japanese: '消える', hiragana: 'きえる', romaji: 'Kieru', german: 'verschwinden / erlöschen', category: 'Verben' },
  { japanese: 'くれる', hiragana: 'くれる', romaji: 'Kureru', german: 'geben (an mich/uns)', category: 'Verben' },
  { japanese: '消す', hiragana: 'けす', romaji: 'Kesu', german: 'ausschalten / löschen / wegradieren', category: 'Verben' },
  { japanese: '答える', hiragana: 'こたえる', romaji: 'Kotaeru', german: 'antworten / beantworten', category: 'Verben' },
  { japanese: '知る', hiragana: 'しる', romaji: 'Shiru', german: 'wissen / kennen / erfahren', category: 'Verben' },
  { japanese: '住む', hiragana: 'すむ', romaji: 'Sumu', german: 'wohnen / leben (an einem Ort)', category: 'Verben' },
  { japanese: '座る', hiragana: 'すわる', romaji: 'Suwaru', german: 'sitzen / sich setzen', category: 'Verben' },
  { japanese: '掃除する', hiragana: 'そうじする', romaji: 'Souji suru', german: 'sauber machen / putzen', category: 'Verben' },
  { japanese: '立つ', hiragana: 'たつ', romaji: 'Tatsu', german: 'aufstehen / stehen', category: 'Verben' },
  { japanese: '頼む', hiragana: 'たのむ', romaji: 'Tanomu', german: 'bitten / bestellen / beauftragen', category: 'Verben' },
  { japanese: '疲れる', hiragana: 'つかれる', romaji: 'Tsukareru', german: 'müde werden / erschöpft sein', category: 'Verben' },
  { japanese: '着く', hiragana: 'つく', romaji: 'Tsuku', german: 'ankommen / erreichen', category: 'Verben' },
  { japanese: '付ける', hiragana: 'つける', romaji: 'Tsukeru', german: 'anmachen / einschalten / befestigen', category: 'Verben' },
  { japanese: '手伝う', hiragana: 'てつだう', romaji: 'Tetsudau', german: 'helfen / mithelfen', category: 'Verben' },
  { japanese: '泊まる', hiragana: 'とまる', romaji: 'Tomaru', german: 'übernachten / anhalten', category: 'Verben' },
  { japanese: '取る', hiragana: 'とる', romaji: 'Toru', german: 'nehmen / greifen / erhalten', category: 'Verben' },
  { japanese: '撮る', hiragana: 'とる', romaji: 'Toru (shashin)', german: 'fotografieren (Foto machen)', category: 'Verben' },
  { japanese: '習う', hiragana: 'ならう', romaji: 'Narau', german: 'lernen (von jemandem) / erlernen', category: 'Verben' },
  { japanese: 'なる', hiragana: 'なる', romaji: 'Naru', german: 'werden / entstehen', category: 'Verben' },
  { japanese: '脱ぐ', hiragana: 'ぬぐ', romaji: 'Nugu', german: 'ausziehen (Kleidung)', category: 'Verben' },
  { japanese: '乗る', hiragana: 'のる', romaji: 'Noru', german: 'einsteigen / fahren mit (Bus, Zug…)', category: 'Verben' },
  { japanese: '始まる', hiragana: 'はじまる', romaji: 'Hajimaru', german: 'beginnen / anfangen (intransitiv)', category: 'Verben' },
  { japanese: '始める', hiragana: 'はじめる', romaji: 'Hajimeru', german: 'beginnen / anfangen (transitiv)', category: 'Verben' },
  { japanese: '働く', hiragana: 'はたらく', romaji: 'Hataraku', german: 'arbeiten / tätig sein', category: 'Verben' },
  { japanese: '弾く', hiragana: 'ひく', romaji: 'Hiku', german: 'spielen (Instrument: Klavier, Gitarre…)', category: 'Verben' },
  { japanese: '持つ', hiragana: 'もつ', romaji: 'Motsu', german: 'halten / tragen / besitzen', category: 'Verben' },
  { japanese: 'もらう', hiragana: 'もらう', romaji: 'Morau', german: 'erhalten / bekommen (von jemandem)', category: 'Verben' },
  { japanese: '休む', hiragana: 'やすむ', romaji: 'Yasumu', german: 'ausruhen / fehlen (Schule/Arbeit)', category: 'Verben' },
  { japanese: '呼ぶ', hiragana: 'よぶ', romaji: 'Yobu', german: 'rufen / einladen / nennen', category: 'Verben' },
  { japanese: '忘れる', hiragana: 'わすれる', romaji: 'Wasureru', german: 'vergessen', category: 'Verben' },
  { japanese: '出す', hiragana: 'だす', romaji: 'Dasu', german: 'herausnehmen / einreichen / abschicken', category: 'Verben' },
  { japanese: '運ぶ', hiragana: 'はこぶ', romaji: 'Hakobu', german: 'tragen / transportieren', category: 'Verben' },
  { japanese: '曲がる', hiragana: 'まがる', romaji: 'Magaru', german: 'abbiegen / sich biegen', category: 'Verben' },
  { japanese: '見せる', hiragana: 'みせる', romaji: 'Miseru', german: 'zeigen / vorführen', category: 'Verben' },
  { japanese: '戻る', hiragana: 'もどる', romaji: 'Modoru', german: 'zurückkehren / zurückgehen', category: 'Verben' },
  { japanese: '笑う', hiragana: 'わらう', romaji: 'Warau', german: 'lachen / lächeln', category: 'Verben' },
  { japanese: '泣く', hiragana: 'なく', romaji: 'Naku', german: 'weinen / heulen', category: 'Verben' },
  { japanese: '怒る', hiragana: 'おこる', romaji: 'Okoru', german: 'wütend werden / sich ärgern', category: 'Verben' },
  { japanese: '着る', hiragana: 'きる', romaji: 'Kiru', german: 'anziehen (Oberteil / Jacke)', category: 'Verben' },
  { japanese: 'はく', hiragana: 'はく', romaji: 'Haku', german: 'anziehen (Hose, Schuhe, Socken)', category: 'Verben' },
  { japanese: '送る', hiragana: 'おくる', romaji: 'Okuru', german: 'schicken / senden / begleiten', category: 'Verben' },
  { japanese: '作る', hiragana: 'つくる', romaji: 'Tsukuru', german: 'machen / herstellen / kochen', category: 'Verben' },
  { japanese: '選ぶ', hiragana: 'えらぶ', romaji: 'Erabu', german: 'auswählen / aussuchen', category: 'Verben' },
  { japanese: '押す', hiragana: 'おす', romaji: 'Osu', german: 'drücken / schieben', category: 'Verben' },
  { japanese: '引く', hiragana: 'ひく', romaji: 'Hiku', german: 'ziehen / nachschlagen (Wörterbuch)', category: 'Verben' },
  { japanese: '直す', hiragana: 'なおす', romaji: 'Naosu', german: 'reparieren / korrigieren / verbessern', category: 'Verben' },
  { japanese: '聞こえる', hiragana: 'きこえる', romaji: 'Kikoeru', german: 'hörbar sein / sich hören lassen', category: 'Verben' },
  { japanese: '見える', hiragana: 'みえる', romaji: 'Mieru', german: 'sichtbar sein / zu sehen sein', category: 'Verben' },
  { japanese: '探す', hiragana: 'さがす', romaji: 'Sagasu', german: 'suchen / nach etw. suchen', category: 'Verben' },
  { japanese: '走る', hiragana: 'はしる', romaji: 'Hashiru', german: 'rennen / laufen (schnell)', category: 'Verben' },
  { japanese: '登る', hiragana: 'のぼる', romaji: 'Noboru', german: 'hochsteigen / klettern', category: 'Verben' },
  { japanese: '降りる', hiragana: 'おりる', romaji: 'Oriru', german: 'aussteigen / heruntersteigen', category: 'Verben' },
  { japanese: '並ぶ', hiragana: 'ならぶ', romaji: 'Narabu', german: 'sich anstellen / in Reihe stehen', category: 'Verben' },
  { japanese: '喜ぶ', hiragana: 'よろこぶ', romaji: 'Yorokobu', german: 'sich freuen / erfreut sein', category: 'Verben' },
  { japanese: '泳ぐ', hiragana: 'およぐ', romaji: 'Oyogu', german: 'schwimmen', category: 'Verben' },
  { japanese: '飛ぶ', hiragana: 'とぶ', romaji: 'Tobu', german: 'fliegen / springen', category: 'Verben' },
  { japanese: '教える', hiragana: 'おしえる', romaji: 'Oshieru', german: 'lehren / beibringen / erklären', category: 'Verben' },
  { japanese: '借りる', hiragana: 'かりる', romaji: 'Kariru', german: 'ausleihen / borgen (von jemandem)', category: 'Verben' },
  { japanese: '変える', hiragana: 'かえる', romaji: 'Kaeru', german: 'ändern / wechseln / verändern', category: 'Verben' },

  // ========== Grundwörter (Erweiterung) ==========
  { japanese: '人', hiragana: 'ひと', romaji: 'Hito', german: 'Person / Mensch', category: 'Grundwörter' },
  { japanese: '物', hiragana: 'もの', romaji: 'Mono', german: 'Sache / Ding / Objekt', category: 'Grundwörter' },
  { japanese: 'こと', hiragana: 'こと', romaji: 'Koto', german: 'Angelegenheit / Tatsache (abstrakt)', category: 'Grundwörter' },
  { japanese: '所', hiragana: 'ところ', romaji: 'Tokoro', german: 'Ort / Stelle / Punkt', category: 'Grundwörter' },
  { japanese: '時', hiragana: 'とき', romaji: 'Toki', german: 'Zeitpunkt / Moment / wenn', category: 'Grundwörter' },
  { japanese: '国', hiragana: 'くに', romaji: 'Kuni', german: 'Land / Nation / Heimat', category: 'Grundwörter' },
  { japanese: '町', hiragana: 'まち', romaji: 'Machi', german: 'Stadt / Ort / Stadtviertel', category: 'Grundwörter' },
  { japanese: 'みんな', hiragana: 'みんな', romaji: 'Minna', german: 'alle / jeder', category: 'Grundwörter' },
  { japanese: 'ちょっと', hiragana: 'ちょっと', romaji: 'Chotto', german: 'ein bisschen / kurz / mal eben', category: 'Grundwörter' },
  { japanese: 'たくさん', hiragana: 'たくさん', romaji: 'Takusan', german: 'viele / viel / reichlich', category: 'Grundwörter' },
  { japanese: '少し', hiragana: 'すこし', romaji: 'Sukoshi', german: 'ein bisschen / etwas / wenig', category: 'Grundwörter' },
  { japanese: 'もっと', hiragana: 'もっと', romaji: 'Motto', german: 'mehr / noch mehr', category: 'Grundwörter' },
  { japanese: '一番', hiragana: 'いちばん', romaji: 'Ichiban', german: 'am meisten / Nummer eins / bestes', category: 'Grundwörter' },
  { japanese: 'とても', hiragana: 'とても', romaji: 'Totemo', german: 'sehr / äußerst', category: 'Grundwörter' },
  { japanese: '本当に', hiragana: 'ほんとうに', romaji: 'Hontouni', german: 'wirklich / tatsächlich', category: 'Grundwörter' },
  { japanese: 'だいたい', hiragana: 'だいたい', romaji: 'Daitai', german: 'ungefähr / im Großen und Ganzen', category: 'Grundwörter' },
  { japanese: 'じゃあ', hiragana: 'じゃあ', romaji: 'Jaa', german: 'dann / also / na gut', category: 'Grundwörter' },
  { japanese: 'でも', hiragana: 'でも', romaji: 'Demo', german: 'aber / jedoch / trotzdem', category: 'Grundwörter' },
  { japanese: 'また', hiragana: 'また', romaji: 'Mata', german: 'wieder / nochmals / außerdem', category: 'Grundwörter' },
  { japanese: 'もう', hiragana: 'もう', romaji: 'Mou', german: 'schon / bereits / gleich', category: 'Grundwörter' },
  { japanese: 'まだ', hiragana: 'まだ', romaji: 'Mada', german: 'noch / noch nicht', category: 'Grundwörter' },
  { japanese: 'すぐ', hiragana: 'すぐ', romaji: 'Sugu', german: 'sofort / gleich / direkt', category: 'Grundwörter' },
  { japanese: 'ぜひ', hiragana: 'ぜひ', romaji: 'Zehi', german: 'unbedingt / auf jeden Fall', category: 'Grundwörter' },
  { japanese: 'たぶん', hiragana: 'たぶん', romaji: 'Tabun', german: 'wahrscheinlich / vielleicht', category: 'Grundwörter' },
  { japanese: 'きっと', hiragana: 'きっと', romaji: 'Kitto', german: 'sicher / bestimmt / gewiss', category: 'Grundwörter' },
  { japanese: 'もちろん', hiragana: 'もちろん', romaji: 'Mochiron', german: 'natürlich / selbstverständlich', category: 'Grundwörter' },
  { japanese: 'よく', hiragana: 'よく', romaji: 'Yoku', german: 'oft / häufig / gut', category: 'Grundwörter' },
  { japanese: '初めて', hiragana: 'はじめて', romaji: 'Hajimete', german: 'zum ersten Mal', category: 'Grundwörter' },
  { japanese: '一人', hiragana: 'ひとり', romaji: 'Hitori', german: 'allein / eine Person', category: 'Grundwörter' },
  { japanese: '二人', hiragana: 'ふたり', romaji: 'Futari', german: 'zwei Personen / zu zweit', category: 'Grundwörter' },
  { japanese: '一緒に', hiragana: 'いっしょに', romaji: 'Issho ni', german: 'zusammen / gemeinsam', category: 'Grundwörter' },
  { japanese: 'ぜんぜん', hiragana: 'ぜんぜん', romaji: 'Zenzen', german: 'überhaupt nicht / gar nicht', category: 'Grundwörter' },
  { japanese: '本当', hiragana: 'ほんとう', romaji: 'Hontou', german: 'Wahrheit / wirklich / echt', category: 'Grundwörter' },
  { japanese: '自分', hiragana: 'じぶん', romaji: 'Jibun', german: 'man selbst / ich / eigene Person', category: 'Grundwörter' },
  { japanese: '方', hiragana: 'ほう', romaji: 'Hou', german: 'Richtung / Seite / Weise', category: 'Grundwörter' },

  // ========== Schule (Erweiterung) ==========
  { japanese: '授業', hiragana: 'じゅぎょう', romaji: 'Jugyou', german: 'Unterrichtsstunde / Lektion', category: 'Schule' },
  { japanese: '宿題', hiragana: 'しゅくだい', romaji: 'Shukudai', german: 'Hausaufgaben', category: 'Schule' },
  { japanese: '試験', hiragana: 'しけん', romaji: 'Shiken', german: 'Prüfung / Test / Klausur', category: 'Schule' },
  { japanese: '卒業', hiragana: 'そつぎょう', romaji: 'Sotsugyou', german: 'Abschluss / Schulabschluss', category: 'Schule' },
  { japanese: '入学', hiragana: 'にゅうがく', romaji: 'Nyuugaku', german: 'Schulaufnahme / Immatrikulation', category: 'Schule' },
  { japanese: 'クラス', hiragana: 'クラス', romaji: 'Kurasu', german: 'Klasse / Kurs', category: 'Schule' },
  { japanese: '友達', hiragana: 'ともだち', romaji: 'Tomodachi', german: 'Freund(in) / Freunde', category: 'Schule' },
  { japanese: '制服', hiragana: 'せいふく', romaji: 'Seifuku', german: 'Schuluniform', category: 'Schule' },
  { japanese: '辞書', hiragana: 'じしょ', romaji: 'Jisho', german: 'Wörterbuch', category: 'Schule' },
  { japanese: '成績', hiragana: 'せいせき', romaji: 'Seiseki', german: 'Note / Ergebnis / Leistung', category: 'Schule' },
  { japanese: '質問', hiragana: 'しつもん', romaji: 'Shitsumon', german: 'Frage / Anfrage', category: 'Schule' },

  // ========== Kleidung (Erweiterung) ==========
  { japanese: '服', hiragana: 'ふく', romaji: 'Fuku', german: 'Kleidung / Kleidungsstück', category: 'Kleidung' },
  { japanese: '着物', hiragana: 'きもの', romaji: 'Kimono', german: 'Kimono (traditionelle Kleidung)', category: 'Kleidung' },
  { japanese: '手袋', hiragana: 'てぶくろ', romaji: 'Tebukuro', german: 'Handschuhe', category: 'Kleidung' },
  { japanese: 'マフラー', hiragana: 'マフラー', romaji: 'Mafuraa', german: 'Schal / Halstuch', category: 'Kleidung' },
  { japanese: 'ネクタイ', hiragana: 'ネクタイ', romaji: 'Nekutai', german: 'Krawatte', category: 'Kleidung' },
  { japanese: 'スーツ', hiragana: 'スーツ', romaji: 'Suutsu', german: 'Anzug', category: 'Kleidung' },
  { japanese: 'セーター', hiragana: 'セーター', romaji: 'Seetaa', german: 'Pullover / Strickpulli', category: 'Kleidung' },
  { japanese: 'コート', hiragana: 'コート', romaji: 'Kooto', german: 'Mantel / Coat', category: 'Kleidung' },
  { japanese: 'パジャマ', hiragana: 'パジャマ', romaji: 'Pajama', german: 'Pyjama / Schlafanzug', category: 'Kleidung' },

  // ========== 100 Kanji (neu) ==========
  { japanese: '一', hiragana: 'いち・ひと', romaji: 'ichi / hito', german: 'eins', category: 'Kanji' },
  { japanese: '二', hiragana: 'に・ふた', romaji: 'ni / futa', german: 'zwei', category: 'Kanji' },
  { japanese: '三', hiragana: 'さん・み', romaji: 'san / mi', german: 'drei', category: 'Kanji' },
  { japanese: '四', hiragana: 'し・よん・よ', romaji: 'shi / yon / yo', german: 'vier', category: 'Kanji' },
  { japanese: '五', hiragana: 'ご・いつ', romaji: 'go / itsu', german: 'fünf', category: 'Kanji' },
  { japanese: '六', hiragana: 'ろく・む', romaji: 'roku / mu', german: 'sechs', category: 'Kanji' },
  { japanese: '七', hiragana: 'しち・なな', romaji: 'shichi / nana', german: 'sieben', category: 'Kanji' },
  { japanese: '八', hiragana: 'はち・や', romaji: 'hachi / ya', german: 'acht', category: 'Kanji' },
  { japanese: '九', hiragana: 'く・きゅう・ここの', romaji: 'ku / kyuu / kokono', german: 'neun', category: 'Kanji' },
  { japanese: '十', hiragana: 'じゅう・とお', romaji: 'juu / too', german: 'zehn', category: 'Kanji' },
  { japanese: '百', hiragana: 'ひゃく', romaji: 'hyaku', german: 'hundert', category: 'Kanji' },
  { japanese: '千', hiragana: 'せん・ち', romaji: 'sen / chi', german: 'tausend', category: 'Kanji' },
  { japanese: '万', hiragana: 'まん・ばん', romaji: 'man / ban', german: 'zehntausend', category: 'Kanji' },
  { japanese: '円', hiragana: 'えん・まる', romaji: 'en / maru', german: 'Yen / Kreis', category: 'Kanji' },
  { japanese: '年', hiragana: 'ねん・とし', romaji: 'nen / toshi', german: 'Jahr', category: 'Kanji' },
  { japanese: '月', hiragana: 'つき・げつ・がつ', romaji: 'tsuki / getsu / gatsu', german: 'Mond / Monat', category: 'Kanji' },
  { japanese: '日', hiragana: 'ひ・にち・じつ', romaji: 'hi / nichi / jitsu', german: 'Sonne / Tag', category: 'Kanji' },
  { japanese: '時', hiragana: 'とき・じ', romaji: 'toki / ji', german: 'Zeit / Stunde / Uhr', category: 'Kanji' },
  { japanese: '分', hiragana: 'ふん・ぷん・ぶん', romaji: 'fun / pun / bun', german: 'Minute / Teil', category: 'Kanji' },
  { japanese: '半', hiragana: 'はん', romaji: 'han', german: 'halb', category: 'Kanji' },
  { japanese: '上', hiragana: 'うえ・かみ・じょう', romaji: 'ue / kami / jou', german: 'oben / auf / über', category: 'Kanji' },
  { japanese: '下', hiragana: 'した・しも・か・げ', romaji: 'shita / shimo / ka / ge', german: 'unten / unter / hinunter', category: 'Kanji' },
  { japanese: '左', hiragana: 'ひだり・さ', romaji: 'hidari / sa', german: 'links', category: 'Kanji' },
  { japanese: '右', hiragana: 'みぎ・う・ゆう', romaji: 'migi / u / yuu', german: 'rechts', category: 'Kanji' },
  { japanese: '中', hiragana: 'なか・ちゅう', romaji: 'naka / chuu', german: 'Mitte / innen / drin', category: 'Kanji' },
  { japanese: '前', hiragana: 'まえ・ぜん', romaji: 'mae / zen', german: 'vorne / vorher / vor', category: 'Kanji' },
  { japanese: '後', hiragana: 'うしろ・あと・ご・こう', romaji: 'ushiro / ato / go / kou', german: 'hinten / nachher / nach', category: 'Kanji' },
  { japanese: '外', hiragana: 'そと・ほか・がい', romaji: 'soto / hoka / gai', german: 'außen / draußen / fremd', category: 'Kanji' },
  { japanese: '北', hiragana: 'きた・ほく', romaji: 'kita / hoku', german: 'Norden', category: 'Kanji' },
  { japanese: '南', hiragana: 'みなみ・なん', romaji: 'minami / nan', german: 'Süden', category: 'Kanji' },
  { japanese: '東', hiragana: 'ひがし・とう', romaji: 'higashi / tou', german: 'Osten', category: 'Kanji' },
  { japanese: '西', hiragana: 'にし・せい・さい', romaji: 'nishi / sei / sai', german: 'Westen', category: 'Kanji' },
  { japanese: '大', hiragana: 'おお・だい・たい', romaji: 'oo / dai / tai', german: 'groß / sehr', category: 'Kanji' },
  { japanese: '小', hiragana: 'ちい・こ・しょう', romaji: 'chii / ko / shou', german: 'klein / wenig', category: 'Kanji' },
  { japanese: '高', hiragana: 'たか・こう', romaji: 'taka / kou', german: 'hoch / teuer', category: 'Kanji' },
  { japanese: '安', hiragana: 'やす・あん', romaji: 'yasu / an', german: 'günstig / sicher / beruhigt', category: 'Kanji' },
  { japanese: '新', hiragana: 'あたら・しん', romaji: 'atara / shin', german: 'neu', category: 'Kanji' },
  { japanese: '古', hiragana: 'ふる・こ', romaji: 'furu / ko', german: 'alt (Dinge)', category: 'Kanji' },
  { japanese: '長', hiragana: 'なが・ちょう', romaji: 'naga / chou', german: 'lang / Chef', category: 'Kanji' },
  { japanese: '多', hiragana: 'おお・た', romaji: 'oo / ta', german: 'viele / viel', category: 'Kanji' },
  { japanese: '少', hiragana: 'すく・すこ・しょう', romaji: 'suku / suko / shou', german: 'wenig / wenige', category: 'Kanji' },
  { japanese: '広', hiragana: 'ひろ・こう', romaji: 'hiro / kou', german: 'weit / breit / geräumig', category: 'Kanji' },
  { japanese: '遠', hiragana: 'とお・えん', romaji: 'too / en', german: 'weit entfernt / fern', category: 'Kanji' },
  { japanese: '近', hiragana: 'ちか・きん', romaji: 'chika / kin', german: 'nah / nahe', category: 'Kanji' },
  { japanese: '早', hiragana: 'はや・そう', romaji: 'haya / sou', german: 'früh / schnell', category: 'Kanji' },
  { japanese: '山', hiragana: 'やま・さん', romaji: 'yama / san', german: 'Berg', category: 'Kanji' },
  { japanese: '川', hiragana: 'かわ・せん', romaji: 'kawa / sen', german: 'Fluss', category: 'Kanji' },
  { japanese: '田', hiragana: 'た・でん', romaji: 'ta / den', german: 'Reisfeld', category: 'Kanji' },
  { japanese: '林', hiragana: 'はやし・りん', romaji: 'hayashi / rin', german: 'Wald (kleiner)', category: 'Kanji' },
  { japanese: '森', hiragana: 'もり・しん', romaji: 'mori / shin', german: 'Wald (großer)', category: 'Kanji' },
  { japanese: '海', hiragana: 'うみ・かい', romaji: 'umi / kai', german: 'Meer / See', category: 'Kanji' },
  { japanese: '空', hiragana: 'そら・から・くう', romaji: 'sora / kara / kuu', german: 'Himmel / leer', category: 'Kanji' },
  { japanese: '花', hiragana: 'はな・か', romaji: 'hana / ka', german: 'Blume / Blüte', category: 'Kanji' },
  { japanese: '木', hiragana: 'き・もく・ぼく', romaji: 'ki / moku / boku', german: 'Baum / Holz', category: 'Kanji' },
  { japanese: '石', hiragana: 'いし・せき', romaji: 'ishi / seki', german: 'Stein / Fels', category: 'Kanji' },
  { japanese: '火', hiragana: 'ひ・か', romaji: 'hi / ka', german: 'Feuer / Dienstag (火曜日)', category: 'Kanji' },
  { japanese: '水', hiragana: 'みず・すい', romaji: 'mizu / sui', german: 'Wasser / Mittwoch (水曜日)', category: 'Kanji' },
  { japanese: '気', hiragana: 'き・け・げ', romaji: 'ki / ke / ge', german: 'Geist / Energie / Luft / Stimmung', category: 'Kanji' },
  { japanese: '雨', hiragana: 'あめ・あま・う', romaji: 'ame / ama / u', german: 'Regen', category: 'Kanji' },
  { japanese: '雪', hiragana: 'ゆき・せつ', romaji: 'yuki / setsu', german: 'Schnee', category: 'Kanji' },
  { japanese: '人', hiragana: 'ひと・じん・にん', romaji: 'hito / jin / nin', german: 'Mensch / Person', category: 'Kanji' },
  { japanese: '口', hiragana: 'くち・こう・く', romaji: 'kuchi / kou / ku', german: 'Mund / Eingang / Öffnung', category: 'Kanji' },
  { japanese: '手', hiragana: 'て・た・しゅ', romaji: 'te / ta / shu', german: 'Hand', category: 'Kanji' },
  { japanese: '足', hiragana: 'あし・そく', romaji: 'ashi / soku', german: 'Fuß / Bein / ausreichend', category: 'Kanji' },
  { japanese: '目', hiragana: 'め・もく・ぼく', romaji: 'me / moku / boku', german: 'Auge / Nummer', category: 'Kanji' },
  { japanese: '耳', hiragana: 'みみ・じ', romaji: 'mimi / ji', german: 'Ohr', category: 'Kanji' },
  { japanese: '父', hiragana: 'ちち・ふ', romaji: 'chichi / fu', german: 'Vater', category: 'Kanji' },
  { japanese: '母', hiragana: 'はは・も・ぼ', romaji: 'haha / mo / bo', german: 'Mutter', category: 'Kanji' },
  { japanese: '子', hiragana: 'こ・し', romaji: 'ko / shi', german: 'Kind', category: 'Kanji' },
  { japanese: '女', hiragana: 'おんな・じょ', romaji: 'onna / jo', german: 'Frau / weiblich', category: 'Kanji' },
  { japanese: '男', hiragana: 'おとこ・だん・なん', romaji: 'otoko / dan / nan', german: 'Mann / männlich', category: 'Kanji' },
  { japanese: '友', hiragana: 'とも・ゆう', romaji: 'tomo / yuu', german: 'Freund / Freundschaft', category: 'Kanji' },
  { japanese: '先', hiragana: 'さき・せん', romaji: 'saki / sen', german: 'vorher / Spitze / Lehrer', category: 'Kanji' },
  { japanese: '生', hiragana: 'いき・う・なま・せい・しょう', romaji: 'iki / u / nama / sei / shou', german: 'Leben / lebendig / roh', category: 'Kanji' },
  { japanese: '学', hiragana: 'まな・がく', romaji: 'mana / gaku', german: 'lernen / Studium / Wissenschaft', category: 'Kanji' },
  { japanese: '校', hiragana: 'こう', romaji: 'kou', german: 'Schule / Schulgebäude', category: 'Kanji' },
  { japanese: '国', hiragana: 'くに・こく', romaji: 'kuni / koku', german: 'Land / Nation / Heimat', category: 'Kanji' },
  { japanese: '語', hiragana: 'かた・ご', romaji: 'kata / go', german: 'Sprache / Wort / erzählen', category: 'Kanji' },
  { japanese: '読', hiragana: 'よ・とく・どく', romaji: 'yo / toku / doku', german: 'lesen', category: 'Kanji' },
  { japanese: '書', hiragana: 'か・しょ', romaji: 'ka / sho', german: 'schreiben / Schrift / Buch', category: 'Kanji' },
  { japanese: '見', hiragana: 'み・けん・げん', romaji: 'mi / ken / gen', german: 'sehen / schauen', category: 'Kanji' },
  { japanese: '聞', hiragana: 'き・もん・ぶん', romaji: 'ki / mon / bun', german: 'hören / fragen', category: 'Kanji' },
  { japanese: '話', hiragana: 'はな・はなし・わ', romaji: 'hana / hanashi / wa', german: 'sprechen / Geschichte / Gespräch', category: 'Kanji' },
  { japanese: '行', hiragana: 'い・おこな・ぎょう・こう', romaji: 'i / okona / gyou / kou', german: 'gehen / tun / Zeile', category: 'Kanji' },
  { japanese: '来', hiragana: 'く・き・らい', romaji: 'ku / ki / rai', german: 'kommen / nächste (Zeit)', category: 'Kanji' },
  { japanese: '帰', hiragana: 'かえ・き', romaji: 'kae / ki', german: 'zurückkehren / heimgehen', category: 'Kanji' },
  { japanese: '入', hiragana: 'い・はい・にゅう', romaji: 'i / hai / nyuu', german: 'eintreten / hinein', category: 'Kanji' },
  { japanese: '出', hiragana: 'で・だ・しゅつ', romaji: 'de / da / shutsu', german: 'ausgehen / heraus / herausgeben', category: 'Kanji' },
  { japanese: '食', hiragana: 'た・しょく', romaji: 'ta / shoku', german: 'essen / Essen / Mahlzeit', category: 'Kanji' },
  { japanese: '飲', hiragana: 'の・いん', romaji: 'no / in', german: 'trinken / Getränk', category: 'Kanji' },
  { japanese: '白', hiragana: 'しろ・はく・びゃく', romaji: 'shiro / haku / byaku', german: 'weiß / leer / gestehen', category: 'Kanji' },
  { japanese: '黒', hiragana: 'くろ・こく', romaji: 'kuro / koku', german: 'schwarz', category: 'Kanji' },
  { japanese: '赤', hiragana: 'あか・せき', romaji: 'aka / seki', german: 'rot', category: 'Kanji' },
  { japanese: '青', hiragana: 'あお・せい・しょう', romaji: 'ao / sei / shou', german: 'blau / grün / jung', category: 'Kanji' },
  { japanese: '車', hiragana: 'くるま・しゃ', romaji: 'kuruma / sha', german: 'Auto / Fahrzeug / Rad', category: 'Kanji' },
  { japanese: '電', hiragana: 'でん', romaji: 'den', german: 'Elektrizität / Strom / Blitz', category: 'Kanji' },
  { japanese: '金', hiragana: 'かね・きん・こん', romaji: 'kane / kin / kon', german: 'Gold / Geld / Freitag (金曜日)', category: 'Kanji' },
  { japanese: '土', hiragana: 'つち・ど・と', romaji: 'tsuchi / do / to', german: 'Erde / Boden / Samstag (土曜日)', category: 'Kanji' },
  { japanese: '天', hiragana: 'あめ・あま・てん', romaji: 'ame / ama / ten', german: 'Himmel / Natur / göttlich', category: 'Kanji' },
  { japanese: '名', hiragana: 'な・めい・みょう', romaji: 'na / mei / myou', german: 'Name / berühmt', category: 'Kanji' },
];

// Migration: rename Japanese category names to German
const CATEGORY_MIGRATIONS: Record<string, string> = {
  'あいさつ': 'Begrüßung',
  '数字':     'Zahlen',
  '時間':     'Zeit',
  '食べ物':   'Essen',
  '飲み物':   'Getränke',
  '家族':     'Familie',
  '体':       'Körper',
  '場所':     'Orte',
  '乗り物':   'Verkehr',
  '自然':     'Natur',
  '動物':     'Tiere',
  '形容詞':   'Adjektive',
  '動詞':     'Verben',
  '基本語':   'Grundwörter',
  '学校':     'Schule',
  '服':       'Kleidung',
};

export async function seed(): Promise<void> {
  await initDb();

  // Run category migration regardless of seed state
  for (const [jp, de] of Object.entries(CATEGORY_MIGRATIONS)) {
    await db.execute({ sql: 'UPDATE vocabulary SET category = ? WHERE category = ?', args: [de, jp] });
  }

  // Insert new entries — skip if (japanese, category) already exists
  let added = 0;
  for (const entry of vocabulary) {
    const exists = await db.execute({
      sql: 'SELECT id FROM vocabulary WHERE japanese = ? AND category = ?',
      args: [entry.japanese, entry.category],
    });
    if (exists.rows.length === 0) {
      const result = await db.execute({
        sql: `INSERT INTO vocabulary (japanese, hiragana, romaji, german, category) VALUES (?, ?, ?, ?, ?)`,
        args: [entry.japanese, entry.hiragana, entry.romaji, entry.german, entry.category],
      });
      await db.execute({
        sql: `INSERT OR IGNORE INTO progress (vocabulary_id, score, review_count, next_review) VALUES (?, 0, 0, datetime('now'))`,
        args: [result.lastInsertRowid],
      });
      added++;
    }
  }

  const total = (await db.execute('SELECT COUNT(*) as c FROM vocabulary')).rows[0]?.c;
  console.log(`🌸 Added ${added} new entries. Total: ${total}.`);
}
